# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
"""
copy_source_assets.py — generate the TlamatiniSourceCode self-modify snapshot.

Called by `build.py --self-modify` (and runnable standalone) to assemble the
COMPLETE source-code tree Tlamatini needs to take -> modify -> integrate ->
regenerate her own Tlamatini.exe, while omitting heavy media and everything
already present (or regenerable) in the installed directory tree.

DEEP ASSET ANALYSIS (what a self-rebuild actually needs)
========================================================

The snapshot mirrors the repo-root layout, so a rebuild is simply:
    cd <install_root>/TlamatiniSourceCode && python build.py --self-modify

INCLUDED — everything the build pipeline and the app's source surface touch:
  * Build pipeline (repo root): build.py, build_installer.py,
    build_uninstaller.py, versioning.py, install.py, uninstall.py,
    regen_secrets.py, requirements.txt, pyinstaller_hooks/, eslint.config.mjs,
    package.json, pnpm-lock.yaml, tlamatini_mcp_server.py, this script itself.
  * Self-update capability ("About > Check for updates"): the in-app updater
    agent/self_update.py AND the external file-swap script apply_update.ps1
    (repo root; build.py ships it next to Tlamatini.exe so self_update.py can
    copy it out and run the swap). Both are plain source and ship verbatim.
  * ALL PowerShell helpers (*.ps1): Tlamatini.ps1, CreateShortcut.ps1,
    RemoveShortcut.ps1, register_flw.ps1, unregister_flw.ps1, apply_update.ps1
    (+ CreateShortcut.json).
  * The full Django tree: every .py, .html, .css, .js, .yaml/.yml, .json,
    .pmt (prompt.pmt + monitoring-prompt.pmt), .proto, SKILL.md packages,
    all 76 agent templates, migrations, tests, AuxTests/.
  * Firmware template sources (.ino/.h/.cpp — ArduinoTemplateProject etc.).
  * Docs that drive behavior or onboarding: CLAUDE.md, docs/claude/*,
    agents_descriptions.md (parsed at runtime for tooltips!), README.md,
    BookOfTlamatini.md, ACPX.md, VERSIONING.md, .agents/, .mcps/, .skills/,
    .claude/ (skills + hooks; settings.local.json EXCLUDED — secret fragments),
    .github/, LICENSE, .gitignore, .mcp.json.
  * Small build-REQUIRED binaries: *.ico (build.py --icon + console icon,
    ~39 KB x2), *.wav (notification/hypervisor sounds shipped via
    --add-data static, ~730 KB total), *.svg (spinner). A rebuild FAILS or
    produces a degraded app without these, so they ship despite being binary.

EXCLUDED — heavy media, secrets, and regenerable/duplicated state:
  * Media: .pdf, .pptx, .png, .jpg/.jpeg, .gif, .mp4 ... (~44 MB — the
    agent/images gallery, demo videos, presentation, summary PDF). None are
    inputs to PyInstaller except agent/static/agent/video/XAIHT-Tlamatini.mp4,
    which is listed in the RESTORE manifest (copy back from the installed
    _internal/agent/static tree before rebuilding).
  * jd-cli/jd-cli.jar (3.8 MB) — already at <install_root>/jd-cli verbatim;
    listed in the RESTORE manifest (build.py hard-requires it).
  * Tlamatini/staticfiles/ — regenerated by `manage.py collectstatic`
    (rebuild instruction), never a source of truth.
  * Secrets & local state: data.keys, db.sqlite3, .claude/settings.local.json,
    key.txt/cookie.txt/crumb.json, *.session, *.log, *.pos, _version.py,
    *.version.txt, .build.lock, pkg.zip/*.zip, *.exe/*.dll/*.pyd, *.lnk.
  * Dev/derived trees: .git, __pycache__, node_modules, venv/.venv, build/,
    dist/, agents/pools/, Temp/, Templates/, content_generated/,
    context_files/, applications/, caches — and TlamatiniSourceCode itself
    (recursion guard).
  * SECRET REDACTION: agent/config.json and the agent config.yaml files may
    carry LIVE keys on a dev machine. Values for secret-looking keys are
    replaced with the regen_secrets.py placeholder style "<KEY goes here>";
    at rebuild time Tlamatini restores them from the installed config.json
    (see _REBUILD_INSTRUCTIONS.md written into the snapshot).

The snapshot also gets `_SOURCE_SNAPSHOT_MANIFEST.json` (counts, sizes,
restore list, redacted-file list) and `_REBUILD_INSTRUCTIONS.md` (the exact
restore + rebuild runbook Tlamatini follows).

Usage:
    python copy_source_assets.py                       # -> Tlamatini/agent/TlamatiniSourceCode
    python copy_source_assets.py --dest <dir>          # -> custom destination
    python copy_source_assets.py --no-redact           # keep secrets verbatim (LOCAL ONLY)

From build.py:
    import copy_source_assets
    stats = copy_source_assets.copy_source_assets(repo_root, dest_dir)
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parent

DEFAULT_DEST = REPO_ROOT / "Tlamatini" / "agent" / "TlamatiniSourceCode"

# ── Exclusion rules ──────────────────────────────────────────────────────────

# Directory NAMES skipped wherever they appear in the tree.
EXCLUDED_DIR_NAMES = {
    ".git", "__pycache__", "node_modules", ".venv", "venv", "env",
    ".ruff_cache", ".pytest_cache", ".mypy_cache", ".pyre", ".pytype",
    "htmlcov", ".idea", ".vscode", ".eggs",
    "build", "dist",                  # PyInstaller outputs
    "pools",                          # agent runtime pools (state, not source)
    "staticfiles",                    # regenerated by collectstatic
    "Temp", "Templates",              # runtime scratch / scaffolded projects
    "security_logs",                  # security defender alert logs + asset-test run artifacts (runtime state)
    "content_generated", "context_files", "applications",
    "agents_backup",                  # self-update one-generation backup of agents/
    "updater",                        # self-update staging/run dir (apply_update.ps1)
    "TlamatiniSourceCode",            # recursion guard — never snapshot a snapshot
    "python",                         # <repo>/python: source-tree build Python (carried-source artifact, gitignored)
    "Go", "gopath", "go-build",       # Discoverer's private Go toolchain + caches (gitignored **/Go/; ~150 MB of READ-ONLY module-cache files — never snapshot)
}

# File EXTENSIONS skipped everywhere (lowercase, with dot).
EXCLUDED_EXTENSIONS = {
    # documents / presentations
    ".pdf", ".pptx", ".ppt",
    # images (NOTE: .ico and .svg are deliberately KEPT — build-required)
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".tif", ".tiff",
    # audio/video (NOTE: .wav is deliberately KEPT — shipped UI sounds)
    ".mp4", ".avi", ".mov", ".mkv", ".webm", ".mp3", ".ogg", ".flac",
    # archives / binaries
    ".zip", ".7z", ".gz", ".rar", ".jar", ".exe", ".dll", ".pyd", ".so",
    ".lnk", ".msi",
    # generated / local state
    ".sqlite3", ".log", ".session", ".pos", ".lock", ".pyc", ".pyo",
    ".spec", ".manifest", ".mo", ".pot",
}

# Exact file NAMES skipped wherever they appear.
EXCLUDED_FILE_NAMES = {
    "db.sqlite3", "data.keys", "key.txt", "cookie.txt", "crumb.json",
    "package-lock.json", "settings.local.json", "_version.py",
    ".build.lock", "Thumbs.db", ".DS_Store",
    # PII / private local state (gitignored) — NEVER snapshot. contacts.private.json
    # holds Angela's REAL phone numbers (the private build bundles it as the install's
    # contacts.json via TLAMATINI_BUNDLE_CONTACTS — it is user data, not source);
    # .private_targets.json is her leak-target list (names/phones/emails); a live
    # contacts.json is user state a rebuild never needs (build.py regenerates it).
    "contacts.private.json", "contacts.json",
    ".private_targets.json", "private_targets.json",
    # Leak-audit artifacts (gitignored) — carry found-secret SAMPLES by design,
    # so shipping them into the snapshot re-leaks what they flagged.
    "private_data_audit_report.json", "personal_info_audit_report.md",
    "public_release_verify_report.json",
}

# Glob patterns (matched against the file name) skipped everywhere.
EXCLUDED_FILE_GLOBS = ("*.version.txt", "*_log.txt", "*_log.log")

# ── Credential files — HARD DROP, never resurrectable ────────────────────────
# This walk reads the WORKING TREE, not git. So a .gitignore'd secret file is
# still physically on disk and WAS being copied into TlamatiniSourceCode/ — and
# from there into pkg.zip, and out to every user of a `--self-modify` build.
# Git history stays clean while the BUILD leaks: exactly the hole found live on
# 2026-07-31, when the snapshot was carrying `open_router.key` (a real OpenRouter
# sk-or-v1 key) and `.creds.env` (the chat-test TLAMATINI_USER/PASS login).
# A rebuild NEVER needs a credential file — build.py reads none of these.
# Enforced in the SAME tier as EXCLUDED_FILE_NAMES (i.e. BEFORE KEEP_PATH_GLOBS),
# so a KEEP carve-out can never resurrect a secret.
SECRET_FILE_EXTENSIONS = {
    ".key", ".keys", ".pem", ".p12", ".pfx", ".jks", ".keystore",
    ".env",                      # covers "*.env" (e.g. .creds.env)
    ".asc", ".gpg", ".ppk",
}

# Name globs for credential files an extension test cannot see: `Path(".env").suffix`
# is "" (a leading dot makes the whole name a STEM), so a bare `.env` needs a name
# rule. Kept deliberately NARROW — a tempting `*_secrets.*` would silently drop
# `regen_secrets.py`, a REQUIRED build script.
SECRET_FILE_GLOBS = (
    ".env", ".env.*",
    "id_rsa", "id_rsa.*", "id_ed25519", "id_ed25519.*",
)

# ── DROP carve-outs (path-based) ─────────────────────────────────────────────
# Snapshot-relative POSIX path globs ALWAYS dropped: run artifacts that are
# neither source nor a build input, and that a rebuild never reads. Kept narrow
# and PATH-anchored on purpose — a bare "reports" entry in EXCLUDED_DIR_NAMES
# would be far too broad and could drop real source elsewhere in the tree.
DROP_PATH_GLOBS = (
    # dated chat-test run artifacts (gitignored; ~1.2 MB of HTML/JSONL per sweep)
    ".claude/skills/tlamatini-daily-chat-test/harness/reports/**",
)

# ── KEEP carve-outs (path-based) ─────────────────────────────────────────────
# Snapshot-relative POSIX path globs whose files are KEPT even when
# EXCLUDED_EXTENSIONS / EXCLUDED_FILE_GLOBS would drop them. Same rationale as
# the global .ico / .wav / .svg keeps: these are SMALL, SHIPPED assets the app
# and its shipped docs reference BY NAME, so a rebuild without them produces a
# visibly broken Tlamatini — they are source, not media.
#   * static/agent/img/**       -> the chat-avatar frames referenced from
#                                  agent_page.html via {% static %} (~152 KB).
#   * agents/*/guide_assets/**  -> the setup screenshots embedded in the shipped
#                                  HOW_TO_GET_YOUR_*_ASSETS.md guides (~1.2 MB).
# Deliberately NOT covered: static/agent/video/** (large, restore-mapped) and
# agent/images/** (the ~70 MB gallery — optional, degrades gracefully).
# EXCLUDED_FILE_NAMES (secrets / PII / local state) is NEVER overridden here.
KEEP_PATH_GLOBS = (
    "Tlamatini/agent/static/agent/img/**",
    "Tlamatini/agent/agents/*/guide_assets/**",
)

# ── Completeness guarantee ───────────────────────────────────────────────────
# The walk is generic (any new .py/.yaml/.js/... ships automatically), but a
# careless future exclusion rule could silently drop a build- or run-critical
# source. These snapshot-relative paths MUST land in every snapshot; a missing
# one raises rather than producing a quietly-incomplete self-modify tree.
# Add the canonical file of any new always-present capability here.
REQUIRED_SNAPSHOT_FILES = (
    # Build + packaging pipeline
    "build.py",
    "build_installer.py",
    "build_uninstaller.py",
    "versioning.py",
    "requirements.txt",
    "copy_source_assets.py",
    # Self-update capability (in-app checker + external file-swap script)
    "apply_update.ps1",
    "Tlamatini/agent/self_update.py",
    # Core app source + LLM identity
    "Tlamatini/agent/config.json",
    "Tlamatini/agent/prompt.pmt",
    "Tlamatini/agent/Tlamatini.md",
    "CLAUDE.md",
    # Descripciones de los agents: el inglés es la base y el .es se encima
    # para los tooltips del sidebar y el diálogo de Descripción, así que un
    # External MCP client layer. NOTE: external_mcps.json is gitignored USER
    # STATE (absent in a fresh checkout, redacted if present) — it is NOT a
    # required source file; requiring it wrongly aborted snapshot generation.
    "Tlamatini/agent/external_mcp_manager.py",
    # Always-present capabilities added since the ESPHomer era. Each is the
    # canonical file of a whole subsystem, so a careless future exclusion fails
    # loudly instead of shipping a Tlamatini that cannot rebuild them.
    "Tlamatini/agent/self_healing.py",              # self-healing model steps
    "Tlamatini/agent/cancellation.py",              # per-user run-epoch hard cancel
    "Tlamatini/agent/path_guard.py",                # Temp / Templates directory policy
    "Tlamatini/agent/agent_manifest.py",            # companion-app (FlowPills) discovery
    "Tlamatini/agent/windows_app_registration.py",  # HKCU discovery-key writer
    # Newest agent (Nmapper) — both the script and its template config
    "Tlamatini/agent/agents/nmapper/nmapper.py",
    "Tlamatini/agent/agents/nmapper/config.yaml",
    # KEEP_PATH_GLOBS canaries — shipped binary assets referenced BY NAME that
    # the extension rules would otherwise drop. Without the avatar frame the
    # chat portrait renders broken; without the guide screenshot the shipped
    # HOW_TO_GET_YOUR_*_ASSETS.md walkthroughs lose their images.
    "Tlamatini/agent/static/agent/img/avatar/eo_mc.jpg",
    "Tlamatini/agent/agents/whatsapper/guide_assets/whatsapp_01_meta_create_app.jpg",
)

# ── Restore manifest — binaries the REBUILD needs but the snapshot omits ─────
# Each entry: snapshot-relative target  ->  where to copy it from at rebuild
# time, relative to the INSTALLED Tlamatini root (next to Tlamatini.exe).
RESTORE_FROM_INSTALL = {
    "Tlamatini/jd-cli/jd-cli.jar":
        "jd-cli/jd-cli.jar",
    "Tlamatini/agent/static/agent/video/XAIHT-Tlamatini.mp4":
        "_internal/agent/static/agent/video/XAIHT-Tlamatini.mp4",
}

# ── Secret redaction (mirrors regen_secrets.py placeholder style) ───────────

# A key is secret-looking when its LAST underscore-segment(s) match one of
# these suffixes. Deliberately does NOT match max_tokens / request_timeout /
# device_name / chat history fields.
_SECRET_KEY_RE = re.compile(
    r"(?i)^(?:.*[_\-.])?("
    r"api_key|apikey|api_hash|api_id|token|bot_token|secret|client_secret|"
    r"password|passwd|access_key|chat_id|listen_chat|session_string|username"
    r")$"
)

# YAML line:   <indent><key>: <value>     (comments after the value survive)
_YAML_KV_RE = re.compile(r"^(\s*)([A-Za-z0-9_\-.]+)(\s*:\s*)(.*?)(\s*(#.*)?)$")

_SKIP_VALUES = {"", "''", '""', "[]", "{}", "null", "~", "None", "0"}


def _placeholder(key: str) -> str:
    """regen_secrets.py-compatible placeholder."""
    return f"<{key} goes here>"


def _is_secret_key(key: str) -> bool:
    return bool(_SECRET_KEY_RE.match(key.strip()))


def _value_needs_redaction(value: str) -> bool:
    v = value.strip().strip("'\"")
    if v in _SKIP_VALUES or value.strip() in _SKIP_VALUES:
        return False
    if v.startswith("<") and v.endswith("goes here>"):
        return False  # already a placeholder
    return True


def _redact_json_obj(obj: Any, hits: List[str]) -> Any:
    """Deep-walk a parsed JSON structure replacing secret-looking values."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if (_is_secret_key(str(k)) and isinstance(v, (str, int, float))
                    and _value_needs_redaction(str(v))):
                out[k] = _placeholder(str(k))
                hits.append(str(k))
            else:
                out[k] = _redact_json_obj(v, hits)
        return out
    if isinstance(obj, list):
        return [_redact_json_obj(item, hits) for item in obj]
    return obj


def _redact_json_text(text: str) -> tuple[str, int]:
    """Redact a JSON document; returns (new_text, redaction_count).
    Fail-open: unparseable JSON is returned verbatim with 0 redactions."""
    try:
        data = json.loads(text)
    except Exception:
        return text, 0
    hits: List[str] = []
    redacted = _redact_json_obj(data, hits)
    if not hits:
        return text, 0
    return json.dumps(redacted, indent=2, ensure_ascii=False) + "\n", len(hits)


def _redact_yaml_text(text: str) -> tuple[str, int]:
    """Line-based YAML redaction (comments and formatting survive intact)."""
    out_lines: List[str] = []
    count = 0
    for line in text.splitlines(keepends=False):
        m = _YAML_KV_RE.match(line)
        if m:
            indent, key, sep, value, trail = m.group(1), m.group(2), m.group(3), m.group(4), m.group(5) or ""
            if _is_secret_key(key) and _value_needs_redaction(value):
                out_lines.append(f"{indent}{key}{sep}'{_placeholder(key)}'{trail}")
                count += 1
                continue
        out_lines.append(line)
    new_text = "\n".join(out_lines)
    if text.endswith("\n"):
        new_text += "\n"
    return new_text, count


# The self-modify snapshot must never carry a user's REAL contacts (phone numbers
# / @handles are PII the key-based redactor above does NOT scrub). So contacts.json
# is replaced wholesale with this safe example in the snapshot.
_CONTACTS_SNAPSHOT_PLACEHOLDER = (
    '{\n'
    '  "_README": "Tlamatini Contacts book. Add people here, then say \'send a '
    "WhatsApp / Telegram to <name>'. Fields: name, aliases, telegram (@username "
    'for people), whatsapp (+phone), email.",\n'
    '  "contacts": [\n'
    '    {"name": "Example Person", "aliases": ["Example"], '
    '"telegram": "@example", "whatsapp": "+10000000000", "email": "example@example.com"}\n'
    '  ]\n'
    '}\n'
)


def _wants_redaction(rel_posix: str) -> str:
    """Return 'json' / 'yaml' / 'contacts' / '' for files whose secrets must be scrubbed."""
    if rel_posix == "Tlamatini/agent/config.json":
        return "json"
    if rel_posix == "Tlamatini/agent/external_mcps.json":
        return "json"  # External MCP catalog — a server's env block may hold keys
    if rel_posix == "Tlamatini/agent/contacts.json":
        return "contacts"  # PII (phones / handles) — replace with a safe example
    if (rel_posix.startswith("Tlamatini/agent/agents/")
            and rel_posix.endswith("config.yaml")):
        return "yaml"
    return ""


# ── Walk + copy ──────────────────────────────────────────────────────────────

def _is_kept_by_path(rel_posix: str) -> bool:
    """True when a snapshot-relative POSIX path is explicitly KEPT (see
    KEEP_PATH_GLOBS) despite an extension/glob drop rule."""
    return any(fnmatch.fnmatch(rel_posix, pat) for pat in KEEP_PATH_GLOBS)


def _is_secret_file(name: str) -> bool:
    """True for credential-bearing files (keys / .env / private keys). Checked in
    the same NEVER-resurrected tier as EXCLUDED_FILE_NAMES — see the comment on
    SECRET_FILE_EXTENSIONS for why this must beat every KEEP carve-out."""
    if Path(name).suffix.lower() in SECRET_FILE_EXTENSIONS:
        return True
    return any(fnmatch.fnmatch(name, pat) for pat in SECRET_FILE_GLOBS)


def _is_dropped_by_path(rel_posix: str) -> bool:
    """True when a snapshot-relative POSIX path is ALWAYS dropped (DROP_PATH_GLOBS)."""
    return any(fnmatch.fnmatch(rel_posix, pat) for pat in DROP_PATH_GLOBS)


def _skip_file(name: str, rel_posix: str = "") -> bool:
    # Secrets / PII / local state are NEVER resurrected by a KEEP carve-out.
    if name in EXCLUDED_FILE_NAMES or _is_secret_file(name):
        return True
    # Path-anchored run artifacts (chat-test reports) are dropped before KEEP too.
    if rel_posix and _is_dropped_by_path(rel_posix):
        return True
    # A path-based KEEP wins over the extension / name-glob drops, so shipped UI
    # assets (avatar frames) and shipped-doc screenshots (guide_assets) survive.
    if rel_posix and _is_kept_by_path(rel_posix):
        return False
    if Path(name).suffix.lower() in EXCLUDED_EXTENSIONS:
        return True
    return any(fnmatch.fnmatch(name, pat) for pat in EXCLUDED_FILE_GLOBS)


def _force_remove_readonly(func, path, _exc_info):
    """rmtree onerror hook: some caches (notably Go's module cache) write files
    READ-ONLY on Windows, so clearing a stale snapshot dest can raise WinError 5.
    Clear the read-only bit and retry so a rebuild is never blocked by leftovers."""
    try:
        os.chmod(path, 0o700)
        func(path)
    except Exception:
        pass


def copy_source_assets(repo_root: Path | str = REPO_ROOT,
                       dest: Path | str = DEFAULT_DEST,
                       redact: bool = True) -> Dict[str, Any]:
    """Build the self-modify source snapshot. Returns a stats dict."""
    started = time.time()
    repo_root = Path(repo_root).resolve()
    dest = Path(dest).resolve()
    if dest == repo_root:
        raise ValueError("dest must not be the repo root itself")
    if dest.exists():
        shutil.rmtree(dest, onerror=_force_remove_readonly)
    dest.mkdir(parents=True, exist_ok=True)

    files_copied = 0
    files_skipped = 0
    bytes_copied = 0
    redacted_files: Dict[str, int] = {}
    errors: List[str] = []

    for current_dir, dir_names, file_names in os.walk(repo_root):
        cur = Path(current_dir)
        # prune excluded directories in place (and never descend into dest)
        dir_names[:] = sorted(
            d for d in dir_names
            if d not in EXCLUDED_DIR_NAMES and (cur / d).resolve() != dest
        )
        for fname in sorted(file_names):
            src = cur / fname
            rel = src.relative_to(repo_root)
            rel_posix = rel.as_posix()
            if _skip_file(fname, rel_posix):
                files_skipped += 1
                continue
            dst = dest / rel
            try:
                dst.parent.mkdir(parents=True, exist_ok=True)
                mode = _wants_redaction(rel_posix) if redact else ""
                if mode:
                    text = src.read_text(encoding="utf-8", errors="replace")
                    if mode == "json":
                        new_text, n = _redact_json_text(text)
                    elif mode == "contacts":
                        new_text, n = _CONTACTS_SNAPSHOT_PLACEHOLDER, 1
                    else:
                        new_text, n = _redact_yaml_text(text)
                    dst.write_text(new_text, encoding="utf-8")
                    if n:
                        redacted_files[rel_posix] = n
                else:
                    shutil.copy2(src, dst)
                files_copied += 1
                bytes_copied += dst.stat().st_size
            except OSError as exc:
                errors.append(f"{rel_posix}: {exc}")

    if files_copied == 0:
        raise RuntimeError(f"copy_source_assets produced an EMPTY snapshot at {dest} "
                           f"from {repo_root} — refusing to continue.")

    # Completeness guarantee — fail loudly if a build-/run-critical source was
    # dropped (e.g. by a future exclusion rule) rather than ship a broken tree.
    missing = [rel for rel in REQUIRED_SNAPSHOT_FILES if not (dest / rel).is_file()]
    if missing:
        raise RuntimeError(
            "copy_source_assets snapshot is INCOMPLETE — these required source "
            "files are missing from " + str(dest) + ":\n  - " + "\n  - ".join(missing)
            + "\n(Either the file was removed from the repo, or an exclusion rule "
            "wrongly dropped it — fix before shipping a self-modify build.)"
        )

    stats: Dict[str, Any] = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "repo_root": str(repo_root),
        "dest": str(dest),
        "files_copied": files_copied,
        "files_skipped": files_skipped,
        "bytes_copied": bytes_copied,
        "megabytes_copied": round(bytes_copied / 1048576, 2),
        "files_redacted": len(redacted_files),
        "redactions": redacted_files,
        "restore_from_install": RESTORE_FROM_INSTALL,
        "errors": errors,
        "seconds": round(time.time() - started, 1),
    }

    (dest / "_SOURCE_SNAPSHOT_MANIFEST.json").write_text(
        json.dumps(stats, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (dest / "_REBUILD_INSTRUCTIONS.md").write_text(
        _rebuild_instructions(), encoding="utf-8")
    return stats


def _rebuild_instructions() -> str:
    restore_lines = "\n".join(
        f"   - copy `<install_root>/{src}`  ->  `{dst}` (under this directory)"
        for dst, src in RESTORE_FROM_INSTALL.items()
    )
    return f"""# How to rebuild Tlamatini from this source snapshot

This directory is a COMPLETE source snapshot generated by `copy_source_assets.py`
(omitting media, secrets, and binaries already present in the installed tree).
`<install_root>` below = the installed Tlamatini directory (where Tlamatini.exe lives).

1. **Restore the omitted binaries** (they were skipped because the install
   already carries them):
{restore_lines}

2. **Restore live secrets** — `Tlamatini/agent/config.json` (and a few agent
   `config.yaml` files) here carry `<KEY goes here>` placeholders. Copy the real
   values from `<install_root>/config.json` (and the installed agents' configs),
   or run `python regen_secrets.py --mode keyed` with a populated `data.keys`.

3. **Install build deps** into a Python 3.12.10 interpreter:
   `python -m pip install -r requirements.txt` (build.py also re-installs them).

4. **Regenerate static files** if needed: `python Tlamatini/manage.py collectstatic
   --noinput` (build.py expects `Tlamatini/staticfiles/`).

5. **Build**: `python build.py --self-modify` (then `python build_uninstaller.py`
   and `python build_installer.py` for the full installer pipeline). The
   `--self-modify` flag re-runs `copy_source_assets.py`, so the NEW build's
   snapshot automatically reflects every modification made here.
"""


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--repo-root", default=str(REPO_ROOT),
                        help="Source repository root (default: this script's directory)")
    parser.add_argument("--dest", default=str(DEFAULT_DEST),
                        help=f"Snapshot destination (default: {DEFAULT_DEST})")
    parser.add_argument("--no-redact", action="store_true",
                        help="Keep secret values verbatim (LOCAL USE ONLY)")
    args = parser.parse_args(argv)

    stats = copy_source_assets(args.repo_root, args.dest, redact=not args.no_redact)
    print(f"Snapshot: {stats['dest']}")
    print(f"  files copied   : {stats['files_copied']}")
    print(f"  files skipped  : {stats['files_skipped']}")
    print(f"  size           : {stats['megabytes_copied']} MB")
    print(f"  files redacted : {stats['files_redacted']}")
    if stats["errors"]:
        print(f"  ERRORS ({len(stats['errors'])}):")
        for e in stats["errors"]:
            print(f"    - {e}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
