# -*- coding: utf-8 -*-
# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesearch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'filesearch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ilesearch.proto\x12\nfilesearch\"k\n\rSearchRequest\x12\x1a\n\rbase_path_key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0c\x66ile_pattern\x18\x02 \x01(\t\x12\x16\n\x0einclude_hidden\x18\x03 \x01(\x08\x42\x10\n\x0e_base_path_key\"<\n\x0eSearchResponse\x12\x13\n\x0b\x66ound_files\x18\x01 \x03(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x11\n\x0fListDirsRequest\"\xa2\x01\n\x10ListDirsResponse\x12\x43\n\x0c\x61llowed_dirs\x18\x01 \x03(\x0b\x32-.filesearch.ListDirsResponse.AllowedDirsEntry\x12\x15\n\rerror_message\x18\x02 \x01(\t\x1a\x32\n\x10\x41llowedDirsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa6\x01\n\x0c\x46ileSearcher\x12\x46\n\x0bSearchFiles\x12\x19.filesearch.SearchRequest\x1a\x1a.filesearch.SearchResponse\"\x00\x12N\n\x0fListAllowedDirs\x12\x1b.filesearch.ListDirsRequest\x1a\x1c.filesearch.ListDirsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filesearch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTDIRSRESPONSE_ALLOWEDDIRSENTRY']._loaded_options = None
  _globals['_LISTDIRSRESPONSE_ALLOWEDDIRSENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=32
  _globals['_SEARCHREQUEST']._serialized_end=139
  _globals['_SEARCHRESPONSE']._serialized_start=141
  _globals['_SEARCHRESPONSE']._serialized_end=201
  _globals['_LISTDIRSREQUEST']._serialized_start=203
  _globals['_LISTDIRSREQUEST']._serialized_end=220
  _globals['_LISTDIRSRESPONSE']._serialized_start=223
  _globals['_LISTDIRSRESPONSE']._serialized_end=385
  _globals['_LISTDIRSRESPONSE_ALLOWEDDIRSENTRY']._serialized_start=335
  _globals['_LISTDIRSRESPONSE_ALLOWEDDIRSENTRY']._serialized_end=385
  _globals['_FILESEARCHER']._serialized_start=388
  _globals['_FILESEARCHER']._serialized_end=554
# @@protoc_insertion_point(module_scope)
