# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
# agent/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST

from . import views


def secure_get(view_func):
    return login_required(view_func)


def secure_post(view_func):
    protected_view = csrf_protect(require_POST(view_func))
    protected_view.csrf_exempt = False
    return login_required(protected_view)


urlpatterns = [
    path('', views.login_view, name='home'),
    path('agent/', secure_get(views.agent_page), name='agent_page'),
    path('welcome/', secure_get(views.welcome_view), name='welcome'),
    path('logout/', views.logout_view, name='logout'),
    path('load_canvas/<str:filename>/', secure_get(views.load_canvas_view), name='load_canvas'),
    path('load_prompt/<str:prompt_name>/', secure_get(views.load_prompt_view), name='load_prompt'),
    path('list_prompts/', secure_get(views.list_prompts_view), name='list_prompts'),
    path('load_omissions/<str:omission_name>/', secure_get(views.load_omissions_view), name='load_omissions'),
    path('load_mcp/<str:mcp_name>/', secure_get(views.load_mcp_view), name='load_mcp'),
    path('load_tool/<str:tool_name>/', secure_get(views.load_tool_view), name='load_tool'),
    path('load_agent/<str:agent_name>/', secure_get(views.load_agent_view), name='load_agent'),
    path('load_agent_description/<str:agent_name>/', secure_get(views.load_agent_description_view), name='load_agent_description'),
    path('list_all_agent_descriptions/', secure_get(views.list_all_agent_descriptions_view), name='list_all_agent_descriptions'),
    path('load_agent_config/<str:agent_name>/', secure_get(views.load_agent_config_view), name='load_agent_config'),
    path('agentic_control_panel/', secure_get(views.agentic_control_panel), name='agentic_control_panel'),
    path('save_agent_config/<str:agent_name>/', secure_post(views.save_agent_config_view), name='save_agent_config'),
    path('clear_pool/', secure_post(views.clear_pool_view), name='clear_pool'),
    path('cleanup_session/', secure_post(views.cleanup_session_view), name='cleanup_session'),
    path('clear_agent_logs/', secure_post(views.clear_all_agent_logs_view), name='clear_agent_logs'),
    path('delete_agent_pool_dir/<str:agent_name>/', secure_post(views.delete_agent_pool_dir_view), name='delete_agent_pool_dir'),
    path('deploy_agent_template/<str:agent_name>/', secure_post(views.deploy_agent_template_view), name='deploy_agent_template'),
    path('ensure_agent_exists/<str:agent_name>/', secure_post(views.ensure_agent_exists_view), name='ensure_agent_exists'),
    path('load_config_section/<str:section>/', secure_get(views.load_config_section_view), name='load_config_section'),
    path('save_config_models/', secure_post(views.save_config_models_view), name='save_config_models'),
    path('save_config_urls/', secure_post(views.save_config_urls_view), name='save_config_urls'),
    path('access_keys_wizard/', secure_get(views.access_keys_wizard_view), name='access_keys_wizard'),
    path('save_access_keys_wizard/', secure_post(views.save_access_keys_wizard_view), name='save_access_keys_wizard'),
    path('check_backup_directory/', secure_get(views.check_backup_directory_view), name='check_backup_directory'),
    path('backup_db/', secure_post(views.backup_db_view), name='backup_db'),
    path('pick_backup_directory/', secure_get(views.pick_backup_directory_view), name='pick_backup_directory'),
    path('check_set_db_file/', secure_get(views.check_set_db_file_view), name='check_set_db_file'),
    path('set_db/', secure_post(views.set_db_view), name='set_db'),
    path('pick_db_sqlite_file/', secure_get(views.pick_db_sqlite_file_view), name='pick_db_sqlite_file'),
    path('pick_context_directory/', secure_get(views.pick_context_directory_view), name='pick_context_directory'),
    path('paste_image/', secure_post(views.paste_image_view), name='paste_image'),
    path('tts/', secure_post(views.tts_view), name='tts'),
    path('tts_status/', secure_get(views.tts_status_view), name='tts_status'),
    path('compile_flow/', secure_post(views.compile_flow_view), name='compile_flow'),
    path('flow_from_tool_calls/', secure_post(views.flow_from_tool_calls_view), name='flow_from_tool_calls'),
    path('redact_flow_snapshot/', secure_post(views.redact_flow_snapshot_view), name='redact_flow_snapshot'),
    path('agent_contracts/', secure_get(views.agent_contracts_view), name='agent_contracts'),
    path('version/', views.version_view, name='version'),
    path('check_update/', secure_get(views.check_update_view), name='check_update'),
    path('start_update/', secure_post(views.start_update_view), name='start_update'),
    path('update_status/', secure_get(views.update_status_view), name='update_status'),
    path('update_raiser_connection/<str:agent_name>/', secure_post(views.update_raiser_connection_view), name='update_raiser_connection'),
    path('update_emailer_connection/<str:agent_name>/', secure_post(views.update_emailer_connection_view), name='update_emailer_connection'),
    path('update_monitor_log_connection/<str:agent_name>/', secure_post(views.update_monitor_log_connection_view), name='update_monitor_log_connection'),
    path('update_ender_connection/<str:agent_name>/', secure_post(views.update_ender_connection_view), name='update_ender_connection'),
    path('update_starter_connection/<str:agent_name>/', secure_post(views.update_starter_connection_view), name='update_starter_connection'),
    path('update_whatsapper_connection/<str:agent_name>/', secure_post(views.update_whatsapper_connection_view), name='update_whatsapper_connection'),
    path('update_or_agent_connection/<str:agent_name>/', secure_post(views.update_or_agent_connection_view), name='update_or_agent_connection'),
    path('update_and_agent_connection/<str:agent_name>/', secure_post(views.update_and_agent_connection_view), name='update_and_agent_connection'),
    path('update_croner_connection/<str:agent_name>/', secure_post(views.update_croner_connection_view), name='update_croner_connection'),
    path('update_mover_connection/<str:agent_name>/', secure_post(views.update_mover_agent_connection), name='update_mover_agent_connection'),
    path('update_sleeper_connection/<str:agent_name>/', secure_post(views.update_sleeper_connection_view), name='update_sleeper_connection'),
    path('update_cleaner_connection/<str:agent_name>/', secure_post(views.update_cleaner_connection_view), name='update_cleaner_connection'),
    path('update_deleter_connection/<str:agent_name>/', secure_post(views.update_deleter_connection_view), name='update_deleter_connection'),
    path('update_notifier_connection/<str:agent_name>/', secure_post(views.update_notifier_connection_view), name='update_notifier_connection'),
    path('update_executer_connection/<str:agent_name>/', secure_post(views.update_executer_connection_view), name='update_executer_connection'),
    path('update_pythonxer_connection/<str:agent_name>/', secure_post(views.update_pythonxer_connection_view), name='update_pythonxer_connection'),
    path('update_stopper_connection/<str:agent_name>/', secure_post(views.update_stopper_connection_view), name='update_stopper_connection'),
    path('update_recmailer_connection/<str:agent_name>/', secure_post(views.update_recmailer_connection_view), name='update_recmailer_connection'),
    path('asker_choice/<str:agent_name>/', secure_post(views.asker_choice_view), name='asker_choice'),
    path('execute_starter_agent/<str:agent_name>/', secure_post(views.execute_starter_agent_view), name='execute_starter_agent'),
    path('check_starter_log/<str:agent_name>/', secure_get(views.check_starter_log_view), name='check_starter_log'),
    path('execute_ender_agent/<str:agent_name>/', secure_post(views.execute_ender_agent_view), name='execute_ender_agent'),
    path('check_ender_log/<str:agent_name>/', secure_get(views.check_ender_log_view), name='check_ender_log'),
    path('check_agents_running/<str:agent_name>/', secure_get(views.check_agents_running_view), name='check_agents_running'),
    path('session_state/', secure_get(views.load_session_state_view), name='load_session_state'),
    path('save_session_state/', secure_post(views.save_session_state_view), name='save_session_state'),
    path('clear_session_state/', secure_post(views.clear_session_state_view), name='clear_session_state'),
    path('check_all_agents_status/', secure_get(views.check_all_agents_status_view), name='check_all_agents_status'),
    path('check_chat_runtimes_status/', secure_get(views.check_chat_runtimes_status_view), name='check_chat_runtimes_status'),
    path('read_agent_log/<str:agent_name>/', secure_get(views.read_agent_log_view), name='read_agent_log'),
    path('restart_agent/<str:agent_name>/', secure_post(views.restart_agent_view), name='restart_agent'),
    path('clear_pos_files/', secure_post(views.clear_pos_files_view), name='clear_pos_files'),
    path('get_session_running_processes/', secure_get(views.get_session_running_processes_view), name='get_session_running_processes'),
    path('kill_session_processes/', secure_post(views.kill_session_processes_view), name='kill_session_processes'),
    path('restart_agents/', secure_post(views.restart_agents_view), name='restart_agents'),
    path('reanimate_agents/', secure_post(views.reanimate_agents_view), name='reanimate_agents'),
    path('save_paused_agents/', secure_post(views.save_paused_agents_view), name='save_paused_agents'),
    path('load_paused_agents/', secure_get(views.load_paused_agents_view), name='load_paused_agents'),
    path('delete_paused_agents/', secure_post(views.delete_paused_agents_view), name='delete_paused_agents'),
    path('update_asker_connection/<str:agent_name>/', secure_post(views.update_asker_connection_view), name='update_asker_connection'),
    path('update_forker_connection/<str:agent_name>/', secure_post(views.update_forker_connection_view), name='update_forker_connection'),
    path('update_counter_connection/<str:agent_name>/', secure_post(views.update_counter_connection_view), name='update_counter_connection'),
    path('flash_window/', secure_post(views.flash_window_view), name='flash_window'),
    path('update_shoter_connection/<str:agent_name>/', secure_post(views.update_shoter_connection_view), name='update_shoter_connection'),
    path('update_camcorder_connection/<str:agent_name>/', secure_post(views.update_camcorder_connection_view), name='update_camcorder_connection'),
    path('update_globber_connection/<str:agent_name>/', secure_post(views.update_globber_connection_view), name='update_globber_connection'),
    path('update_grepper_connection/<str:agent_name>/', secure_post(views.update_grepper_connection_view), name='update_grepper_connection'),
    path('update_editor_connection/<str:agent_name>/', secure_post(views.update_editor_connection_view), name='update_editor_connection'),
    path('update_recorder_connection/<str:agent_name>/', secure_post(views.update_recorder_connection_view), name='update_recorder_connection'),
    path('update_whisperer_connection/<str:agent_name>/', secure_post(views.update_whisperer_connection_view), name='update_whisperer_connection'),
    path('update_audioplayer_connection/<str:agent_name>/', secure_post(views.update_audioplayer_connection_view), name='update_audioplayer_connection'),
    path('update_videoplayer_connection/<str:agent_name>/', secure_post(views.update_videoplayer_connection_view), name='update_videoplayer_connection'),
    path('update_talker_connection/<str:agent_name>/', secure_post(views.update_talker_connection_view), name='update_talker_connection'),
    path('update_ssher_connection/<str:agent_name>/', secure_post(views.update_ssher_connection_view), name='update_ssher_connection'),
    path('update_scper_connection/<str:agent_name>/', secure_post(views.update_scper_connection_view), name='update_scper_connection'),
    path('update_teletlamatini_connection/<str:agent_name>/', secure_post(views.update_teletlamatini_connection_view), name='update_teletlamatini_connection'),
    path('update_acpxer_connection/<str:agent_name>/', secure_post(views.update_acpxer_connection_view), name='update_acpxer_connection'),
    path('update_telegrammer_connection/<str:agent_name>/', secure_post(views.update_telegrammer_connection_view), name='update_telegrammer_connection'),
    path('update_sqler_connection/<str:agent_name>/', secure_post(views.update_sqler_connection_view), name='update_sqler_connection'),
    path('update_prompter_connection/<str:agent_name>/', secure_post(views.update_prompter_connection_view), name='update_prompter_connection'),
    path('update_gitter_connection/<str:agent_name>/', secure_post(views.update_gitter_connection_view), name='update_gitter_connection'),
    path('update_dockerer_connection/<str:agent_name>/', secure_post(views.update_dockerer_connection_view), name='update_dockerer_connection'),
    path('update_mcp_doctor_connection/<str:agent_name>/', secure_post(views.update_mcp_doctor_connection_view), name='update_mcp_doctor_connection'),
    path('update_instant_messaging_doctor_connection/<str:agent_name>/', secure_post(views.update_instant_messaging_doctor_connection_view), name='update_instant_messaging_doctor_connection'),
    path('update_pser_connection/<str:agent_name>/', secure_post(views.update_pser_connection_view), name='update_pser_connection'),
    path('execute_flowcreator/<str:agent_name>/', secure_post(views.execute_flowcreator_view), name='execute_flowcreator'),
    path('check_flowcreator_result/<str:agent_name>/', secure_get(views.check_flowcreator_result_view), name='check_flowcreator_result'),
    path('clean_pool_except/<str:agent_name>/', secure_post(views.clean_pool_except_view), name='clean_pool_except'),
    path('update_kuberneter_connection/<str:agent_name>/', secure_post(views.update_kuberneter_connection_view), name='update_kuberneter_connection'),
    path('update_apirer_connection/<str:agent_name>/', secure_post(views.update_apirer_connection_view), name='update_apirer_connection'),
    path('update_unrealer_connection/<str:agent_name>/', secure_post(views.update_unrealer_connection_view), name='update_unrealer_connection'),
    path('update_blenderer_connection/<str:agent_name>/', secure_post(views.update_blenderer_connection_view), name='update_blenderer_connection'),
    path('update_playwrighter_connection/<str:agent_name>/', secure_post(views.update_playwrighter_connection_view), name='update_playwrighter_connection'),
    path('update_reviewer_connection/<str:agent_name>/', secure_post(views.update_reviewer_connection_view), name='update_reviewer_connection'),
    path('update_analyzer_connection/<str:agent_name>/', secure_post(views.update_analyzer_connection_view), name='update_analyzer_connection'),
    path('update_jenkinser_connection/<str:agent_name>/', secure_post(views.update_jenkinser_connection_view), name='update_jenkinser_connection'),
    path('update_crawler_connection/<str:agent_name>/', secure_post(views.update_crawler_connection_view), name='update_crawler_connection'),
    path('update_summarizer_connection/<str:agent_name>/', secure_post(views.update_summarizer_connection_view), name='update_summarizer_connection'),
    path('update_flowhypervisor_connection/<str:agent_name>/', secure_post(views.update_flowhypervisor_connection_view), name='update_flowhypervisor_connection'),
    path('update_mouser_connection/<str:agent_name>/', secure_post(views.update_mouser_connection_view), name='update_mouser_connection'),
    path('update_windower_connection/<str:agent_name>/', secure_post(views.update_windower_connection_view), name='update_windower_connection'),
    path('update_kalier_connection/<str:agent_name>/', secure_post(views.update_kalier_connection_view), name='update_kalier_connection'),
    path('update_zavuerer_connection/<str:agent_name>/', secure_post(views.update_zavuerer_connection_view), name='update_zavuerer_connection'),
    path('update_discoverer_connection/<str:agent_name>/', secure_post(views.update_discoverer_connection_view), name='update_discoverer_connection'),
    path('update_nmapper_connection/<str:agent_name>/', secure_post(views.update_nmapper_connection_view), name='update_nmapper_connection'),
    path('update_pdfer_connection/<str:agent_name>/', secure_post(views.update_pdfer_connection_view), name='update_pdfer_connection'),
    path('update_stm32er_connection/<str:agent_name>/', secure_post(views.update_stm32er_connection_view), name='update_stm32er_connection'),
    path('update_esp32er_connection/<str:agent_name>/', secure_post(views.update_esp32er_connection_view), name='update_esp32er_connection'),
    path('update_esphomer_connection/<str:agent_name>/', secure_post(views.update_esphomer_connection_view), name='update_esphomer_connection'),
    path('update_arduiner_connection/<str:agent_name>/', secure_post(views.update_arduiner_connection_view), name='update_arduiner_connection'),
    path('execute_flowhypervisor/<str:agent_name>/', secure_post(views.execute_flowhypervisor_view), name='execute_flowhypervisor'),
    path('check_flowhypervisor_alert/<str:agent_name>/', secure_get(views.check_flowhypervisor_alert_view), name='check_flowhypervisor_alert'),
    path('validate_flow/', secure_get(views.validate_flow_view), name='validate_flow'),
    path('update_file_interpreter_connection/<str:agent_name>/', secure_post(views.update_file_interpreter_connection_view), name='update_file_interpreter_connection'),
    path('update_image_interpreter_connection/<str:agent_name>/', secure_post(views.update_image_interpreter_connection_view), name='update_image_interpreter_connection'),
    path('update_video_analyzer_connection/<str:agent_name>/', secure_post(views.update_video_analyzer_connection_view), name='update_video_analyzer_connection'),
    path('update_gatewayer_connection/<str:agent_name>/', secure_post(views.update_gatewayer_connection_view), name='update_gatewayer_connection'),
    path('update_gateway_relayer_connection/<str:agent_name>/', secure_post(views.update_gateway_relayer_connection_view), name='update_gateway_relayer_connection'),
    path('update_node_manager_connection/<str:agent_name>/', secure_post(views.update_node_manager_connection_view), name='update_node_manager_connection'),
    path('update_file_creator_connection/<str:agent_name>/', secure_post(views.update_file_creator_connection_view), name='update_file_creator_connection'),
    path('update_file_extractor_connection/<str:agent_name>/', secure_post(views.update_file_extractor_connection_view), name='update_file_extractor_connection'),
    path('update_kyber_keygen_connection/<str:agent_name>/', secure_post(views.update_kyber_keygen_connection_view), name='update_kyber_keygen_connection'),
    path('update_kyber_cipher_connection/<str:agent_name>/', secure_post(views.update_kyber_cipher_connection_view), name='update_kyber_cipher_connection'),
    path('update_kyber_decipher_connection/<str:agent_name>/', secure_post(views.update_kyber_decipher_connection_view), name='update_kyber_decipher_connection'),
    path('update_parametrizer_connection/<str:agent_name>/', secure_post(views.update_parametrizer_connection_view), name='update_parametrizer_connection'),
    path('get_parametrizer_dialog_data/<str:agent_name>/', secure_get(views.get_parametrizer_dialog_data_view), name='get_parametrizer_dialog_data'),
    path('save_parametrizer_scheme/<str:agent_name>/', secure_post(views.save_parametrizer_scheme_view), name='save_parametrizer_scheme'),
    path('update_flowbacker_connection/<str:agent_name>/', secure_post(views.update_flowbacker_connection_view), name='update_flowbacker_connection'),
    path('update_barrier_connection/<str:agent_name>/', secure_post(views.update_barrier_connection_view), name='update_barrier_connection'),
    path('update_j_decompiler_connection/<str:agent_name>/', secure_post(views.update_j_decompiler_connection_view), name='update_j_decompiler_connection'),
    path('update_de_compresser_connection/<str:agent_name>/', secure_post(views.update_de_compresser_connection_view), name='update_de_compresser_connection'),
    path('detect_installed_apps/', secure_get(views.detect_installed_apps_view), name='detect_installed_apps'),
    path('open_in_app/', secure_post(views.open_in_app_view), name='open_in_app'),
    path('update_keyboarder_connection/<str:agent_name>/', secure_post(views.update_keyboarder_connection_view), name='update_keyboarder_connection'),
    path('update_googler_connection/<str:agent_name>/', secure_post(views.update_googler_connection_view), name='update_googler_connection'),
    # ── ACPX-Skills admin (browse + diagnostics + reload) ──
    # Toggle (enable/disable) goes through the existing WebSocket `set-skills`
    # channel for symmetry with Mcps/Agents/Tools; HTTP here is read-mostly.
    path('skills/', secure_get(views.list_skills_view), name='list_skills'),
    path('skills/<str:skill_name>/', secure_get(views.skill_detail_view), name='skill_detail'),
    path('skills/_/reload/', secure_post(views.reload_skills_view), name='reload_skills'),
    path('skills/_/diagnostics/', secure_get(views.skills_diagnostics_view), name='skills_diagnostics'),
    path('external_mcps/', secure_get(views.external_mcps_list_view), name='external_mcps_list'),
    path('external_mcps/activate/', secure_post(views.external_mcps_activate_view), name='external_mcps_activate'),
    path('external_mcps/import/', secure_post(views.external_mcps_import_view), name='external_mcps_import'),
    path('external_mcps/remove/', secure_post(views.external_mcps_remove_view), name='external_mcps_remove'),
    # ── Contacts book CRUD (Config ▸ Contacts dialog over contacts.json) ──
    path('contacts/', secure_get(views.contacts_list_view), name='contacts_list'),
    path('contacts/save/', secure_post(views.contacts_save_view), name='contacts_save'),
]
