#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
"""
sweep_self_modify.py -- deterministic auditor for Tlamatini's self-MODIFY snapshot.

Backs the `tlamatini-self-modify-inclusion` skill. Where the self-UPDATE sweep guards
the runnable release, THIS guards the SOURCE tree a self-able-modify build ships
(`TlamatiniSourceCode/`, generated by `copy_source_assets.py`) so a running Tlamatini
can read -> modify -> rebuild herself. The acid test: *can `python build.py
--self-modify` succeed using ONLY the snapshot + the documented restore steps?*

It actually GENERATES a snapshot into <root>/Temp and verifies, rather than guessing:

  1. GENERATE OK       copy_source_assets runs, REQUIRED_SNAPSHOT_FILES present, no errors
  2. BUILD INPUTS      every file build.py consumes is IN the snapshot, OR in
                       RESTORE_FROM_INSTALL, OR an intentionally-omitted regenerable dir
  3. REDACTION         no live secret survives in the snapshot's config.json / config.yaml
  4. RESTORE MANIFEST  _REBUILD_INSTRUCTIONS.md + manifest exist; each restore source is real
  5. EXCLUSION SANITY  no "source-like" extension is in the EXCLUDED set (a dropped code type)
  6. BUILD SCRIPTS     the whole build pipeline + requirements ship in the snapshot

Pure stdlib, fail-soft. Exit code = number of findings (0 == clean), so it can gate a
self-modify build.

Usage:
    python .claude/skills/tlamatini-self-modify-inclusion/scripts/sweep_self_modify.py
    python .../sweep_self_modify.py --repo-root /path --keep   # keep the generated snapshot
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import shutil
import sys
from pathlib import Path

_FINDINGS: list[str] = []
_NOTES: list[str] = []

# Paths build.py only REFERENCES to create or delete (outputs / transient state),
# never reads as a source input — must not be flagged as "missing from snapshot".
BUILD_ARTIFACT_NAMES = {".build.lock", "manage.spec", "pkg.zip"}
BUILD_ARTIFACT_EXT = {".spec", ".lock"}

# Build-pipeline scripts a rebuild-from-snapshot needs at the repo root.
BUILD_SCRIPTS = (
    "build.py", "build_installer.py", "build_uninstaller.py", "versioning.py",
    "install.py", "uninstall.py", "copy_source_assets.py", "regen_secrets.py",
    "requirements.txt",
)

# Extensions that are "source/code/build-input" and must NEVER be excluded.
SOURCE_LIKE_EXT = {
    ".py", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".vue", ".css", ".scss",
    ".html", ".htm", ".yaml", ".yml", ".json", ".toml", ".ini", ".cfg", ".pmt",
    ".proto", ".ps1", ".md", ".txt", ".ino", ".h", ".hpp", ".c", ".cpp", ".pyx",
}

# Common live-secret value shapes (defence-in-depth beyond key-name redaction).
SECRET_VALUE_RE = re.compile(
    r"(sk-[A-Za-z0-9]{20,}|AIza[0-9A-Za-z_\-]{30,}|ghp_[A-Za-z0-9]{30,}|"
    r"xox[baprs]-[A-Za-z0-9-]{10,}|AKIA[0-9A-Z]{16})"
)


def finding(msg: str) -> None:
    _FINDINGS.append(msg)
    print(f"  [FINDING] {msg}")


def ok(msg: str) -> None:
    print(f"  [PASS]    {msg}")


def note(msg: str) -> None:
    _NOTES.append(msg)
    print(f"  [note]    {msg}")


def _load_csa(root: Path):
    """Import the repo's copy_source_assets.py as a module."""
    path = root / "copy_source_assets.py"
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("copy_source_assets", path)
    if not spec or not spec.loader:
        return None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ── build.py input extraction ────────────────────────────────────────────────

def _extract_literal_block(text: str, name: str) -> str:
    """Return the raw text inside `name = [ ... ]` / `( ... )`, bracket-depth aware,
    skipping comments and string contents (so a ')' in a comment can't end it early)."""
    m = re.search(rf"{re.escape(name)}\s*=\s*([\[(])", text)
    if not m:
        return ""
    i, depth, n = m.end(), 1, len(text)
    buf: list[str] = []
    while i < n and depth > 0:
        ch = text[i]
        if ch == "#":
            j = text.find("\n", i)
            i = n if j == -1 else j
            continue
        if ch in ("'", '"'):
            q = ch
            buf.append(ch)
            i += 1
            while i < n and text[i] != q:
                buf.append(text[i])
                i += 1
            if i < n:
                buf.append(text[i])
                i += 1
            continue
        if ch in "[(":
            depth += 1
        elif ch in "])":
            depth -= 1
            if depth == 0:
                break
        buf.append(ch)
        i += 1
    return "".join(buf)


def _quoted(s: str) -> list[str]:
    return re.findall(r"""['"]([^'"]+)['"]""", s)


def build_inputs(build_txt: str) -> set[str]:
    """Best-effort set of repo-relative paths that build.py reads as inputs."""
    inputs: set[str] = set()

    # support_files (root-level scripts/icons/data shipped next to the exe)
    inputs.update(_quoted(_extract_literal_block(build_txt, "support_files")))

    # --add-data=<SRC>{separator}DEST  and  --add-data=<SRC>;DEST (literal src only)
    for src in re.findall(r"--add-data=([^;{}'\"\s]+)\{separator\}", build_txt):
        inputs.add(src)
    for src in re.findall(r"--add-data=([^;{}'\"\s]+);", build_txt):
        inputs.add(src)

    # --icon=<path>
    for ic in re.findall(r"--icon[=\s]+([^\s'\";]+)", build_txt):
        inputs.add(ic)

    # Path("X") / "Y" / "Z" chains used by *_file_copies / optional_dir_copies / db_path
    for m in re.finditer(r"""Path\(\s*["']([^"']+)["']\s*\)((?:\s*/\s*["'][^"']+["'])*)""", build_txt):
        head = m.group(1)
        tail = re.findall(r"""/\s*["']([^"']+)["']""", m.group(2) or "")
        inputs.add("/".join([head, *tail]))

    # normalise separators and strip trailing slashes
    return {p.replace("\\", "/").rstrip("/") for p in inputs if p and not p.startswith("{")}


# ── checks ───────────────────────────────────────────────────────────────────

def check_redaction(csa, snap: Path) -> None:
    """Re-run csa's own secret detection on the GENERATED snapshot; anything still
    'needs redaction' means redaction failed. Plus a raw secret-value scan."""
    import json as _json

    leaked = 0
    cfg = snap / "Tlamatini" / "agent" / "config.json"
    if cfg.is_file():
        try:
            data = _json.loads(cfg.read_text(encoding="utf-8", errors="replace"))

            def walk(o):
                nonlocal leaked
                if isinstance(o, dict):
                    for k, v in o.items():
                        if (csa._is_secret_key(str(k)) and isinstance(v, (str, int, float))
                                and csa._value_needs_redaction(str(v))):
                            finding(f"unredacted secret in snapshot config.json: key '{k}'")
                            leaked += 1
                        else:
                            walk(v)
                elif isinstance(o, list):
                    for it in o:
                        walk(it)
            walk(data)
        except Exception as exc:
            note(f"could not parse snapshot config.json for redaction check: {exc}")

    for yml in snap.glob("Tlamatini/agent/agents/*/config.yaml"):
        try:
            for line in yml.read_text(encoding="utf-8", errors="replace").splitlines():
                m = csa._YAML_KV_RE.match(line)
                if m and csa._is_secret_key(m.group(2)) and csa._value_needs_redaction(m.group(4)):
                    finding(f"unredacted secret in {yml.relative_to(snap).as_posix()}: key '{m.group(2)}'")
                    leaked += 1
        except OSError:
            continue

    # Raw value-shape scan over CONFIG-type files only. copy_source_assets redacts
    # config.json + agent config.yaml by design (not code), so scanning .py/.txt just
    # trips over test fixtures (e.g. the canonical AWS example key). Whitelist the
    # well-known docs/dummy values so a real leak still stands out.
    known_examples = {"AKIAIOSFODNN7EXAMPLE"}
    for f in snap.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in {".json", ".yaml", ".yml", ".env", ".ini", ".cfg", ".toml"}:
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for hit in SECRET_VALUE_RE.findall(text):
            if hit in known_examples:
                continue
            finding(f"live-looking secret value in snapshot {f.relative_to(snap).as_posix()}: "
                    f"'{hit[:8]}...'")
            leaked += 1

    if leaked == 0:
        ok("no live secret survives in the snapshot (config.json / agent config.yaml / raw scan)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Audit Tlamatini's self-modify source snapshot.")
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--keep", action="store_true", help="Keep the generated snapshot for inspection.")
    args = parser.parse_args(argv)

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    if args.repo_root:
        root = Path(args.repo_root).resolve()
    else:
        here = Path(__file__).resolve()
        root = here.parents[4] if len(here.parents) >= 5 else Path.cwd()

    print(f"Repo root: {root}\n")

    csa = _load_csa(root)
    if csa is None:
        finding("cannot import copy_source_assets.py from repo root")
        print("\nAborting.")
        return len(_FINDINGS)

    build_py = root / "build.py"
    if not build_py.is_file():
        finding("build.py missing at repo root")
        return len(_FINDINGS)
    build_txt = build_py.read_text(encoding="utf-8", errors="replace")

    # ── Check 1: generate the snapshot ───────────────────────────────────────
    print("[1] GENERATE -- copy_source_assets produces a complete, error-free snapshot")
    snap = root / "Temp" / "_self_modify_sweep"
    stats = None
    try:
        stats = csa.copy_source_assets(root, snap, redact=True)
        errs = stats.get("errors") or []
        ok(f"generated {stats['files_copied']} files, {stats['megabytes_copied']} MB, "
           f"{stats['files_redacted']} redacted, {len(errs)} errors")
        for e in errs:
            finding(f"copy error during generation: {e}")
    except Exception as exc:
        finding(f"snapshot generation FAILED: {exc}")
        print("\nAborting: cannot verify a snapshot that won't generate.")
        return len(_FINDINGS)

    # ── Check 6 (early, needs snapshot): build scripts present ────────────────
    print("\n[6] BUILD SCRIPTS -- the rebuild pipeline ships in the snapshot")
    for s in BUILD_SCRIPTS:
        present = (snap / s).is_file()
        (ok if present else finding)(
            f"{s} {'present' if present else 'MISSING -- a rebuild from the snapshot cannot run'}")

    # ── Check 2: every build input survives (or is restorable) ───────────────
    print("\n[2] BUILD INPUTS -- everything build.py consumes is carried (or restorable)")
    restore_targets = {t.replace("\\", "/") for t in getattr(csa, "RESTORE_FROM_INSTALL", {})}
    excluded_dirs = set(getattr(csa, "EXCLUDED_DIR_NAMES", set()))
    media_ext = set(getattr(csa, "EXCLUDED_EXTENSIONS", set()))
    inputs = build_inputs(build_txt)
    checked = covered = 0
    for rel in sorted(inputs):
        repo_path = root / rel
        if not repo_path.exists():
            continue  # parse artifact / build-time-only path
        last = rel.split("/")[-1]
        suffix = Path(rel).suffix.lower()
        # build.py CREATES/DELETES these (outputs), it does not read them as source
        if last in BUILD_ARTIFACT_NAMES or suffix in BUILD_ARTIFACT_EXT:
            continue
        checked += 1
        if (snap / rel).exists():
            covered += 1
            continue
        # omitted -> restorable?
        if any(rt == rel or rt.endswith("/" + rel) or rel.endswith(Path(rt).name) for rt in restore_targets):
            covered += 1
            note(f"build input '{rel}' omitted but covered by RESTORE_FROM_INSTALL (restored at rebuild)")
            continue
        top = rel.split("/")[0]
        # intentionally-omitted regenerable directory (staticfiles, snapshot dir, ...)
        if repo_path.is_dir() and (top in excluded_dirs or last in excluded_dirs):
            note(f"build input dir '{rel}' is intentionally omitted (regenerable; "
                 f"confirm _REBUILD_INSTRUCTIONS.md covers it, e.g. collectstatic)")
            continue
        # a directory that vanished only because ALL its files are media -> optional, degrades
        if repo_path.is_dir():
            files = [f for f in repo_path.rglob("*") if f.is_file()]
            source_files = [f for f in files if f.suffix.lower() not in media_ext]
            if files and not source_files:
                note(f"build input dir '{rel}' holds only media (omitted by design). The build "
                     f"copies it OPTIONALLY, so a rebuild degrades (no gallery) rather than fails. "
                     f"Add it to RESTORE_FROM_INSTALL if it must survive a self-rebuild.")
                continue
            finding(f"build input dir '{rel}' lost {len(source_files)} SOURCE file(s) in the "
                    f"snapshot -- a rebuild would be incomplete.")
            continue
        # a single omitted media/binary file the build consumes
        if suffix in media_ext:
            note(f"build input '{rel}' is an omitted media/binary; if the rebuild needs it, "
                 f"add it to RESTORE_FROM_INSTALL.")
            continue
        finding(f"build input '{rel}' is a SOURCE file consumed by build.py but NOT in the "
                f"snapshot and NOT restorable -- a rebuild from the snapshot would fail.")
    ok(f"checked {checked} resolvable source build inputs; {covered} carried/restorable")

    # ── Check 4: restore manifest + instructions ─────────────────────────────
    print("\n[4] RESTORE MANIFEST -- omitted binaries are documented and real")
    man = snap / "_SOURCE_SNAPSHOT_MANIFEST.json"
    instr = snap / "_REBUILD_INSTRUCTIONS.md"
    (ok if man.is_file() else finding)(
        f"_SOURCE_SNAPSHOT_MANIFEST.json {'present' if man.is_file() else 'MISSING'}")
    (ok if instr.is_file() else finding)(
        f"_REBUILD_INSTRUCTIONS.md {'present' if instr.is_file() else 'MISSING'}")
    restore_map = getattr(csa, "RESTORE_FROM_INSTALL", {})
    for target, _src in restore_map.items():
        # the repo equivalent of the omitted binary should exist (proves it's a real omission)
        repo_equiv = root / target
        if repo_equiv.exists():
            ok(f"restore target '{target}' is a real repo binary (correctly omitted + restorable)")
        else:
            note(f"restore target '{target}' not found in repo -- confirm the path is current")

    # ── Check 3: redaction ───────────────────────────────────────────────────
    print("\n[3] REDACTION -- no live secret survives in the snapshot")
    check_redaction(csa, snap)

    # ── Check 5: exclusion sanity ────────────────────────────────────────────
    print("\n[5] EXCLUSION SANITY -- no source-like extension is excluded")
    bad_ext = SOURCE_LIKE_EXT & set(getattr(csa, "EXCLUDED_EXTENSIONS", set()))
    if not bad_ext:
        ok("no source/code/build-input extension appears in EXCLUDED_EXTENSIONS")
    for e in sorted(bad_ext):
        finding(f"extension '{e}' is source-like but listed in EXCLUDED_EXTENSIONS "
                f"-- those files would be dropped from the self-modify tree.")

    # ── cleanup ──────────────────────────────────────────────────────────────
    if not args.keep:
        try:
            shutil.rmtree(snap)
        except OSError:
            pass
    else:
        note(f"snapshot kept at {snap}")

    # ── summary ──────────────────────────────────────────────────────────────
    print("\n" + "=" * 70)
    if _FINDINGS:
        print(f"RESULT: {len(_FINDINGS)} FINDING(S) -- fix before shipping a self-modify build:")
        for f in _FINDINGS:
            print(f"  - {f}")
    else:
        print("RESULT: CLEAN -- the self-modify snapshot carries everything a rebuild needs.")
    if _NOTES:
        print(f"\n({len(_NOTES)} advisory note(s) above -- review, not blocking.)")
    print("=" * 70)
    return len(_FINDINGS)


if __name__ == "__main__":
    sys.exit(main())
