# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
# Generated by Django 5.2.4 on 2026-01-26 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('idAgent', models.IntegerField(primary_key=True, serialize=False)),
                ('agentName', models.CharField(max_length=200)),
                ('agentDescription', models.CharField(max_length=500)),
                ('agentContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProcess',
            fields=[
                ('idAgentProcess', models.IntegerField(primary_key=True, serialize=False)),
                ('agentProcessDescription', models.CharField(max_length=500)),
                ('agentProcessPid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('idAsset', models.IntegerField(primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=200)),
                ('assetDescription', models.CharField(max_length=500)),
                ('assetContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('context_blob', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMProgram',
            fields=[
                ('idProgram', models.IntegerField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=200)),
                ('programLanguage', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('programContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LLMSnippet',
            fields=[
                ('idSnippet', models.IntegerField(primary_key=True, serialize=False)),
                ('snippetName', models.CharField(max_length=200)),
                ('snippetLanguage', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snippetContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mcp',
            fields=[
                ('idMcp', models.IntegerField(primary_key=True, serialize=False)),
                ('mcpName', models.CharField(max_length=200)),
                ('mcpDescription', models.CharField(max_length=500)),
                ('mcpContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Omission',
            fields=[
                ('idOmission', models.IntegerField(primary_key=True, serialize=False)),
                ('omissionName', models.CharField(max_length=200)),
                ('omissionContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('idPrompt', models.IntegerField(primary_key=True, serialize=False)),
                ('promptName', models.CharField(max_length=200)),
                ('promptContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('context_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('context_type', models.CharField(blank=True, max_length=20, null=True)),
                ('context_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('idTool', models.IntegerField(primary_key=True, serialize=False)),
                ('toolName', models.CharField(max_length=200)),
                ('toolDescription', models.CharField(max_length=500)),
                ('toolContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
