# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
# Generated by Django on 2026-02-17

from django.db import migrations
import os


def repopulate_agents(apps, schema_editor):
    Agent = apps.get_model('agent', 'Agent')

    # Locate agents directory relative to this migration file
    # Migration file is in .../agent/migrations/0016_repopulate_all_agents.py
    # Agents dir is in .../agent/agents/

    migration_file_path = os.path.abspath(__file__)
    agent_app_dir = os.path.dirname(os.path.dirname(migration_file_path))  # .../agent/
    agents_dir = os.path.join(agent_app_dir, 'agents')

    if not os.path.isdir(agents_dir):
        # Fallback if directory structure is different (e.g. frozen app)
        return

    # Get all agent folders
    agent_folders = []
    try:
        for item in os.listdir(agents_dir):
            item_path = os.path.join(agents_dir, item)
            # Skip non-directories and the 'pools' directory
            if os.path.isdir(item_path) and item.lower() != 'pools':
                agent_folders.append(item)
    except FileNotFoundError:
        return

    agent_folders.sort()

    # Clear existing agents
    Agent.objects.all().delete()

    # Populate new agents
    for index, folder_name in enumerate(agent_folders, start=1):
        # Create display name logic
        display_name = folder_name.replace('_', ' ')

        # Consistent casing logic
        if len(display_name) <= 3:
            display_name = display_name.upper()
        else:
            display_name = display_name.title()

        # Specific overrides
        if display_name.lower() == 'and':
            display_name = 'AND'
        elif display_name.lower() == 'or':
            display_name = 'OR'
        elif display_name.lower() == 'monitor log':
            display_name = 'Monitor Log'
        elif display_name.lower() == 'monitor netstat':
            display_name = 'Monitor Netstat'

        agent_name = f"agent-{index}"

        Agent.objects.create(
            idAgent=index,
            agentName=agent_name,
            agentDescription=display_name,
            agentContent='true'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_add_shoter'),
    ]

    operations = [
        migrations.RunPython(repopulate_agents),
    ]
