# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#   Created by  Angela López Mendoza · @angelahack1
# ═══════════════════════════════════════════════════════════════════
"""Catalog of Prompts — the NINE missing Step-by-Step section openers.

Angela's rule: **the FIRST prompt of every catalog section is a Step-by-Step
wizard** — a guided flow that performs ONE action, then STOPS and WAITS for the
user's reply (READY / an output / a screenshot) before the next one.

The 2026-07-20 audit found only 4 of 13 sections owned a genuine wizard
(getting_started 1, firmware_iot 69+70, security_recon 97, messaging 83), and
none of the latter three was actually FIRST. Migration 0181 fixed placement by
promoting those into each section's opening slot. This migration closes the
remaining gap: it seeds a purpose-written wizard for the other NINE sections.

PLACEMENT — this is the whole point of `sort_rank`:
  * ids are APPENDED at 98..106 (the standing append-only rule, never renumber),
  * each row gets `sort_rank = 10`, the slot 0181 deliberately RESERVED at the
    top of every section.
So nine prompts appended at the END of the table render at the TOP of nine
different sections. Before 0181 this migration would have been impossible
without renumbering the whole catalog.

EVERY prompt here obeys the same contract:
  * tells the user to tick **Multi-Turn AND Step-by-Step** (and nothing else),
  * states the ONE-action-per-turn / STOP-and-WAIT rule explicitly and up front,
  * names the exact reply string it wants back ("reply READY 2"),
  * drives ONLY wrapped agents that the section's own existing prompts drive,
  * is SAFE — nothing is deleted, nothing is installed, no human is messaged, no
    unauthorised host is contacted, and every file written goes to the app's own
    Temp / Templates directory (the 2026-06-02 directory policy),
  * ends with END-RESPONSE.

Reverse deletes exactly these nine ids.
"""
from django.db import migrations

OPENER_RANK = 10  # the slot migration 0181 reserved at the top of every section

FILES_SEARCH = (
    "Tlamatini, run the FILES & SEARCH GUIDED TOUR, please - a hands-on, "
    "one-action-at-a-time walkthrough of your three file agents: Globber (find files by "
    "name), Grepper (find text inside files) and Editor (change one exact string in a "
    "file). Before sending, tick BOTH the Multi-Turn checkbox AND the Step-by-Step "
    "checkbox in the toolbar.\n\n"
    "STEP-BY-STEP RULES (obey these strictly): perform EXACTLY ONE action per reply, then "
    "STOP and WAIT for me. After each action, show me the result and end your reply with a "
    "single line telling me exactly what to type back to continue (for example: reply "
    "READY 2). Do NOT run the next step until I answer. Never batch two agent calls into "
    "one reply. Never guess a result you did not actually receive - if an agent fails, tell "
    "me plainly what failed and wait for my instruction. Use ONLY these tools: "
    "chat_agent_file_creator, chat_agent_globber, chat_agent_grepper, chat_agent_editor. "
    "Everything happens inside your app Temp directory (the absolute path the system prompt "
    "gives you); call it TEMP below. Nothing outside TEMP is ever touched, nothing is "
    "deleted, no message is sent anywhere.\n\n"
    "STEP 1 - say hello and confirm the workspace. Do NOT call any agent yet. Tell me, in "
    "two or three short lines, the absolute TEMP path you will use, and that the tour will "
    "create a small folder called tour_demo inside it. Then wait for me to reply READY 2.\n\n"
    "STEP 2 - create the first file. Call chat_agent_file_creator with request \"Run File "
    "Creator with file_path='TEMP/tour_demo/notes.txt' and content='project notes -- "
    "status: draft'\". Show me the file path it reports. Then wait for me to reply READY 3.\n\n"
    "STEP 3 - create a second file in a sub-folder. Call chat_agent_file_creator with "
    "request \"Run File Creator with file_path='TEMP/tour_demo/sub/readme.txt' and "
    "content='readme -- status: draft'\". Show me the file path it reports. Then wait for me "
    "to reply READY 4.\n\n"
    "STEP 4 - find the files by name. Call chat_agent_globber with request \"Run Globber "
    "with pattern='**/*.txt', path='TEMP/tour_demo', sort_by='mtime'\". From the "
    "INI_SECTION_GLOBBER block in the run's log_excerpt, report verbatim the status and the "
    "matches count, and list the file paths it returned in the order returned. Do not "
    "re-classify the status. Then wait for me to reply READY 5.\n\n"
    "STEP 5 - search INSIDE the files. Call chat_agent_grepper with request \"Run Grepper "
    "with pattern='status: draft', path='TEMP/tour_demo', glob='*.txt', "
    "output_mode='content'\". From the INI_SECTION_GREPPER block, report verbatim the "
    "status, the matches count, the files_searched count, and each file:line:match line. "
    "Then wait for me to reply READY 6.\n\n"
    "STEP 6 - change one exact string. Call chat_agent_editor with request \"Run Editor with "
    "file_path='TEMP/tour_demo/notes.txt', old_string='status: draft', new_string='status: "
    "final', replace_all=false\". From the INI_SECTION_EDITOR block, report verbatim the "
    "status (edited | not_found | not_unique | noop | error) and the replacements count. "
    "Then wait for me to reply READY 7.\n\n"
    "STEP 7 - prove the edit really landed. Call chat_agent_grepper AGAIN with request \"Run "
    "Grepper with pattern='status: final', path='TEMP/tour_demo', glob='*.txt', "
    "output_mode='content'\" and show me the matching line from notes.txt. Then wait for me "
    "to reply READY 8.\n\n"
    "STEP 8 - wrap up. Do NOT call any agent. Render one HTML table with "
    "class='exec-report-table' titled 'Files &amp; Search Guided Tour - Summary' with columns "
    "step, agent, what it did, status - one row per agent call you actually made (steps 2 to "
    "7), every status verbatim from the agent's own INI_SECTION block. Use light body cells "
    "(background:#ffffff;color:#0f172a). Underneath, print one short line naming the files "
    "that now live under TEMP/tour_demo, and tell me I can delete that folder myself "
    "whenever I want. End with END-RESPONSE."
)

RUN_EXECUTE = (
    "Tlamatini, run the STEP-BY-STEP RUN &amp; EXECUTE WIZARD with me, please.\n\n"
    "BEFORE YOU START: in the toolbar, tick BOTH the Multi-Turn checkbox AND the "
    "Step-by-Step checkbox. Leave ACPX, Ask Execs and Exec Report exactly as they are. "
    "Confirm in one short line that you are running in Step-by-Step mode, then begin with "
    "Step 1.\n\n"
    "HOW YOU MUST BEHAVE (this is the whole point of this wizard):\n"
    "- Give me ONE action at a time. Never batch two actions into a single answer.\n"
    "- After each action, show me the real output you got, then STOP and WAIT until I reply "
    "READY (or paste you the output / a screenshot). Do NOT start the next step on your own.\n"
    "- If a step fails, tell me plainly what failed and what you would try next, then STOP "
    "and WAIT for me.\n"
    "- Use ONLY these tools: chat_agent_executer (shell commands) and chat_agent_pythonxer "
    "(small inline Python). Do not use any other agent.\n"
    "- Everything here is SAFE and local: nothing is deleted, nothing is installed, no host "
    "other than my own machine is contacted, and nobody is messaged.\n"
    "- End EVERY answer, including the single-step ones, with END-RESPONSE.\n\n"
    "THE STEPS:\n\n"
    "Step 1 - With chat_agent_executer, run: ping -n 2 127.0.0.1\n"
    "Show me the output exactly as it came back, verbatim, without summarizing it. Then stop "
    "and wait for my READY.\n\n"
    "Step 2 - With chat_agent_executer, run: netstat -an\n"
    "Do not paste the whole table. Instead tell me ONLY whether the port Tlamatini's web UI "
    "is bound to appears (8000 by default, or whatever django_port is set to), and if it "
    "does, what its exact state is (for example LISTENING or ESTABLISHED), quoting the one "
    "matching line. Then stop and wait for my READY.\n\n"
    "Step 3 - With chat_agent_pythonxer, run a tiny inline Python snippet that prints, one "
    "per line: the Python version, the operating system name, and the current date and time. "
    "Show me its printed output. Then stop and wait for my READY.\n\n"
    "Step 4 - With chat_agent_executer, list the contents of Tlamatini's own Temp directory "
    "(the Temp folder at the application root - this is the only scratch directory you are "
    "allowed to touch). Just list what is there; create nothing, delete nothing. Then stop "
    "and wait for my READY.\n\n"
    "Step 5 - Now that all four actions are done, give me a short HTML table with one row "
    "per step: the step number, the tool used, the exact command or snippet, and SUCCESS or "
    "FAILURE. Keep every body cell light-background with dark text "
    "(background:#ffffff;color:#0f172a). Add two sentences telling me what this proved about "
    "running commands, scripts and Python inside Tlamatini. This is the last step, so no "
    "waiting is needed after it.\n\n"
    "Go ahead with Step 1 only. END-RESPONSE."
)

CODE_GEN = (
    "Tlamatini, run the CODE-GENERATION STEP-BY-STEP WIZARD, please.\n\n"
    "BEFORE you start, tell me to tick BOTH toolbar checkboxes: Multi-Turn AND Step-by-Step. "
    "Leave Exec Report, ACPX and Ask Execs unticked. Do not begin until you have told me "
    "that.\n\n"
    "HOW THIS WIZARD WORKS - this is the rule you must obey above everything else:\n"
    "- You perform EXACTLY ONE action per turn, then you STOP and WAIT for me.\n"
    "- After each action you must (a) say in one short line what you just did, (b) show me "
    "the concrete result (the path you wrote, the matches you found, the output you got), "
    "and (c) ask me to reply READY (or to paste the output / tell you what I want changed) "
    "before you do anything else.\n"
    "- You must NEVER chain two actions in one turn, never 'pre-run' the next step, and "
    "never assume my READY. If you are unsure, ask me instead of guessing.\n"
    "- Every file you create must go under the Templates directory of this Tlamatini "
    "installation, in a folder named GreetKitDemo. Do not write anywhere else, do not delete "
    "anything, do not touch any pre-existing project.\n\n"
    "THE STEPS, in this exact order (ONE per turn):\n\n"
    "Step 1 - Tell me the absolute path of the Templates directory you will use, and the "
    "full path of the GreetKitDemo folder you are about to create inside it. Do NOT create "
    "anything yet. Ask me to reply READY to approve that location.\n\n"
    "Step 2 - Using chat_agent_file_creator, create the file greetkit.py inside "
    "GreetKitDemo. It must contain a small, self-contained Python module with: a module "
    "docstring, a function greet(name) that returns the string 'Hello, &lt;name&gt;!', and a "
    "function greet_all(names) that returns a list of greetings. Follow the code-generation "
    "rule for code blocks. Show me the exact file path you wrote and the code you put in it, "
    "then wait for my READY.\n\n"
    "Step 3 - Using chat_agent_file_creator, create a second file test_greetkit.py in the "
    "same folder, containing three plain asserts that exercise greet and greet_all (no test "
    "framework needed - just asserts and a print('ALL TESTS PASSED') at the end). Show me "
    "the path and the content, then wait for my READY.\n\n"
    "Step 4 - Using chat_agent_globber, list every file that now exists under GreetKitDemo. "
    "Show me the list exactly as the agent returned it, then wait for my READY.\n\n"
    "Step 5 - Using chat_agent_grepper, search the GreetKitDemo folder for the regex 'def ' "
    "and show me the file:line:match results, so I can see both modules' function "
    "definitions. Then wait for my READY.\n\n"
    "Step 6 - Using chat_agent_pythonxer, run test_greetkit.py and show me its output "
    "verbatim. If it fails, DO NOT silently fix it: show me the error and ask me whether you "
    "should repair it. Then wait for my READY.\n\n"
    "Step 7 - Using chat_agent_editor, make ONE surgical change to greetkit.py: change the "
    "greeting text from 'Hello, ' to 'Hola, '. Show me the exact old_string and new_string "
    "you used and confirm the edit was applied, then wait for my READY.\n\n"
    "Step 8 - Using chat_agent_pythonxer, re-run test_greetkit.py so we can see the test now "
    "fail because of the changed text. Show me the output, explain in one line why it "
    "failed, and ask me whether I want you to update the test to match, or to revert "
    "greetkit.py back to 'Hello, '.\n\n"
    "Step 9 - Do whatever I chose in Step 8 (one action only), show me the result, and then "
    "give me a short final summary: the folder you created, the files in it, and the final "
    "state of the tests.\n\n"
    "Rules for the whole wizard: use ONLY chat_agent_file_creator, chat_agent_globber, "
    "chat_agent_grepper, chat_agent_editor and chat_agent_pythonxer. Do not use any "
    "messaging, network, scanning or deletion agent. Do not run any shell command that "
    "touches anything outside GreetKitDemo. Keep every answer short - one action, its "
    "result, one question.\n\n"
    "End with END-RESPONSE."
)

IMAGES = (
    "Tlamatini, run the IMAGES &amp; VISION STEP-BY-STEP WIZARD, please. Before you start, tick "
    "TWO checkboxes in the toolbar: Multi-Turn AND Step-by-Step. Leave ACPX, Ask Execs and "
    "Add internet context unticked.\n\n"
    "This is a GUIDED, ONE-ACTION-AT-A-TIME wizard. You must perform EXACTLY ONE action per "
    "turn, then STOP and WAIT for me to reply before you do anything else. Never chain two "
    "actions in a single answer. Never assume my answer. After every action, tell me in one "
    "short line what you did, then ask me for the exact reply you need and wait.\n\n"
    "Use ONLY these two agents: chat_agent_shoter (screen capture) and "
    "chat_agent_image_interpreter (vision analysis). Do not use any other tool or agent. Do "
    "not delete, move or overwrite any file.\n\n"
    "ACTION 1 - Confirm we are ready. Do NOT call any tool yet. Just tell me which two "
    "agents you will use and what each one does in one sentence each. Then ask me to reply "
    "exactly: READY 1\n\n"
    "ACTION 2 - When I reply READY 1: call chat_agent_shoter ONCE to take a single silent "
    "screenshot of my screen (no viewer popup). Report back ONLY the absolute output_path of "
    "the saved image file. Then ask me to reply exactly: READY 2\n\n"
    "ACTION 3 - When I reply READY 2: do NOT call a tool. Show me the exact prompt_user text "
    "you intend to send to the vision agent, which must be: 'Describe this screenshot: list "
    "every visible GUI element with its approximate position as a percentage of the image, "
    "its approximate size as a percentage, its colour and its exact visible text.' Ask me to "
    "reply exactly READY 3 to accept it, or to paste a replacement instruction if I want a "
    "different question asked about the image.\n\n"
    "ACTION 4 - When I reply READY 3 (or give you my own instruction): call "
    "chat_agent_image_interpreter ONCE, passing images_pathfilenames set to the absolute "
    "path you captured in ACTION 2 and prompt_user set to the accepted instruction. Report "
    "ONLY the status value carried by the INI_SECTION_IMAGE_INTERPRETER block (merged / "
    "partial_interpreter_1_only / partial_interpreter_2_only / merge_fallback_concat) and "
    "how many elements the report found. Then ask me to reply exactly: READY 4\n\n"
    "ACTION 5 - When I reply READY 4: do NOT call a tool. Give me the FIVE most interesting "
    "findings from the merged interpretation, as five short bullet lines, and state which of "
    "the two interpreter models contributed the detail you found most useful. Then tell me "
    "the wizard is complete and remind me I can now try the other prompts in this section on "
    "any image of my own.\n\n"
    "If at any point a step fails, STOP, tell me plainly what failed and what you would need "
    "in order to retry, and WAIT for my instruction - never skip ahead to the next action. "
    "End with END-RESPONSE."
)

AGENTS_FLOWS = (
    "Tlamatini, run the GUIDED FIRST AGENTS wizard, please - a hands-on, "
    "one-action-at-a-time walkthrough that teaches me how your wrapped agents chain "
    "together. Before sending this, tick BOTH the Multi-Turn checkbox AND the Step-by-Step "
    "checkbox in the toolbar (leave ACPX, Ask Execs and Add internet context unticked - this "
    "wizard is fully local and needs none of them).\n\n"
    "HOW THIS WIZARD WORKS - this is the most important rule and it overrides everything "
    "else: you perform EXACTLY ONE action per response, then you STOP and WAIT for me. Never "
    "run two agents in the same turn. Never look ahead to the next step. After each action, "
    "show me what that single agent returned, tell me in one short line what you are about "
    "to do next, and end by asking me to reply READY (or to paste the output you see) before "
    "you continue. If a wrapped agent returns a running run_id, poll it with "
    "chat_agent_run_status and chat_agent_run_log until it finishes - that polling is part "
    "of the SAME step, not a new one. If any step fails, show me the error VERBATIM, do not "
    "improvise a workaround, and wait for my instruction.\n\n"
    "Every file this wizard writes goes into your app Temp directory (the absolute path the "
    "system prompt gives you) - never anywhere else. Nothing is deleted and nobody is "
    "messaged.\n\n"
    "Step 0 (introduce, then wait): open with one short HTML banner reading 'GUIDED FIRST "
    "AGENTS - Step-by-Step' plus a one-sentence explanation that we will build a tiny "
    "four-agent local chain together: File Creator, then File Extractor, then Summarize "
    "Text, then Notifier. Run NO agent in this turn. End by asking me to reply READY.\n\n"
    "Step 1 (File Creator - wait first): when I reply READY, use File Creator to create the "
    "file tlamatini_wizard_notes.txt inside your app Temp directory, containing four or five "
    "short plain-text lines describing what a Tlamatini workflow agent is. Then show me the "
    "exact path it wrote and the byte count in a small HTML table, explain in one line that "
    "the next step will read that same file back with a DIFFERENT agent, and ask me to reply "
    "READY.\n\n"
    "Step 2 (File Extractor - wait first): when I reply READY, use File Extractor on that "
    "exact same path to pull the raw text back out. Show me the extracted text verbatim in a "
    "code block, point out in one line that File Creator wrote it and File Extractor read it "
    "- two separate agents, two separate runtime directories - and ask me to reply READY.\n\n"
    "Step 3 (Summarize Text - wait first): when I reply READY, use Summarize Text on the "
    "text you just extracted to produce a 3-bullet executive summary. Show me the three "
    "bullets, note in one line that this is the first LLM-powered agent in the chain, and "
    "ask me to reply READY.\n\n"
    "Step 4 (Notifier - wait first): when I reply READY, use Notifier to announce with the "
    "title 'Wizard complete' and a one-line message that the guided chain finished. Confirm "
    "the notification fired and ask me to reply READY one last time.\n\n"
    "Step 5 (close): when I reply READY, run NO further agent. Close with one short HTML "
    "banner reading 'WIZARD COMPLETE' and a compact HTML table listing the four agents we "
    "ran in order, what each one did, and the file path they shared. Keep every body cell "
    "light-background with dark text (background:#ffffff;color:#0f172a). Then tell me that "
    "the other prompts in this Agents and Flows section run these same chains unattended in "
    "a single turn - and that I can untick Step-by-Step whenever I want that faster "
    "behaviour.\n\n"
    "Keep every response short. Never batch steps. Never continue without my READY. End with "
    "END-RESPONSE."
)

ACPX_SKILLS = (
    "Tlamatini, run the ACPX &amp; SKILLS GUIDED FIRST CONTACT wizard, please - a safe, "
    "read-only walkthrough that gets me from 'I have never touched ACPX' to 'I know exactly "
    "what is installed on this machine and what I can run next'.\n\n"
    "Before sending: tick the Multi-Turn checkbox AND the Step-by-Step checkbox. Also tick "
    "ACPX (this wizard reads the ACPX runtime). Leave Ask Execs, Exec report and Add "
    "internet context unticked.\n\n"
    "STEP-BY-STEP MODE RULES - follow these strictly:\n"
    "- Perform exactly ONE action, then STOP and WAIT for me.\n"
    "- After each action, show me: (a) what you just ran, (b) the short result in plain "
    "words, and (c) the exact words I should reply to continue (always the single word "
    "READY, unless you need a real answer from me).\n"
    "- NEVER run two steps in one message. NEVER skip ahead because a step looked easy. "
    "NEVER assume my answer.\n"
    "- Everything in this wizard is READ-ONLY. Do NOT spawn any external CLI child, do NOT "
    "write, move or delete any file, do NOT send any message, do NOT run any shell command. "
    "If you ever think you need to, STOP and ask me first.\n"
    "- Use ONLY these tools: chat_agent_mcp_doctor, acp_doctor, list_acp_agents, "
    "list_skills, invoke_skill. Nothing else.\n\n"
    "Here is the wizard, one action per turn:\n\n"
    "ACTION 1 - Is my External MCP catalog healthy?\n"
    "Call chat_agent_mcp_doctor with request \"Run MCP Doctor with server_key=''\" (an empty "
    "server_key triages EVERY catalogued server). Read the JSON return and the "
    "INI_SECTION_MCP_DOCTOR block in log_excerpt. Tell me, in at most four short lines: the "
    "catalog_path, the overall status, how many servers are catalogued, and whether any of "
    "them is currently blocked. Then ask me to reply READY.\n\n"
    "ACTION 2 - Is the ACPX runtime alive?\n"
    "Call acp_doctor. Tell me in at most four short lines: whether ok is true or false, the "
    "active permissionMode, the stateDir, and - if a probe ran - which agent_id was probed. "
    "If ok is false, say plainly that the ACPX runtime is up but no external coding-agent "
    "CLI is installed yet, and that this is normal and not an error. Then ask me to reply "
    "READY.\n\n"
    "ACTION 3 - Which external agents actually resolve on THIS machine?\n"
    "Call list_acp_agents. Show me a small HTML table titled 'ACPX agents on this machine' "
    "with columns agent_id, command, transport and resolvable_here, light body cells "
    "(background:#ffffff;color:#0f172a). Then say one sentence naming which agent_ids I "
    "could actually spawn today, or say 'none yet' if the resolvable column is false "
    "everywhere. Then ask me to reply READY.\n\n"
    "ACTION 4 - What skills do I already have?\n"
    "Call list_skills with no filter. Show me a small HTML table titled 'Skill catalog' with "
    "columns name, description and runtime. Then say one sentence naming which of them run "
    "in-process (no external CLI needed) versus which need ACPX. Then ask me to reply "
    "READY.\n\n"
    "ACTION 5 - Prove a skill really runs.\n"
    "Call invoke_skill with skill_name 'summarize' and args_json '{\"text\":\"ACPX is "
    "Tlamatini runtime for spawning external coding-agent CLIs as child processes, talking "
    "to them over stdin and stdout, persisting the conversation as an NDJSON transcript, and "
    "brokering the whole thing to the LLM as twelve tools. Skills are markdown SKILL.md "
    "packages the LLM invokes by name through list_skills and invoke_skill.\","
    "\"target_words\":35}'. Quote the returned summary verbatim. Then ask me to reply "
    "READY.\n\n"
    "ACTION 6 - Let a skill choose an agent for me.\n"
    "Call invoke_skill with skill_name 'acp-router' and args_json '{\"intent\":\"review a "
    "Python codebase and explain its architecture\"}'. Tell me which agent_id it "
    "recommended, and whether that agent_id was resolvable in ACTION 3. Then ask me to reply "
    "READY.\n\n"
    "ACTION 7 - Final briefing.\n"
    "Do not call any tool. Write me a short closing briefing with exactly three parts:\n"
    "1) READY TO RUN NOW - which prompts of this ACPX, Skills &amp; MCPs section I can run today "
    "with what is installed (the skills-only and doctor-only ones).\n"
    "2) NEEDS ONE INSTALL FIRST - which prompts need an external coding-agent CLI, and name "
    "the single CLI I should install first based on what ACTION 6 recommended.\n"
    "3) THE ONE COMMAND - the exact install command for that CLI, printed for me to copy. Do "
    "NOT run it yourself; I will run it.\n"
    "Then stop.\n\n"
    "End with END-RESPONSE."
)

DESKTOP_UI = (
    "Tlamatini, run the DESKTOP FIRST STEPS wizard, please - a guided, "
    "ONE-ACTION-AT-A-TIME introduction to the desktop-UI agents (Windower, Mouser, "
    "Keyboarder), where YOU do a single action and then WAIT for me before doing anything "
    "else.\n\n"
    "PRECONDITIONS: before sending, tick BOTH the Multi-Turn checkbox AND the Step-by-Step "
    "checkbox in the toolbar (ACPX is NOT required). This demo is Windows-only (Windower "
    "uses the Win32 API, Mouser uses PyAutoGUI). Nothing here installs software, deletes "
    "anything, or contacts anyone - it only opens Notepad, moves that window, types into it, "
    "and closes it WITHOUT saving.\n\n"
    "HOW THIS WIZARD MUST BEHAVE - this is the whole point, do not break it:\n"
    "- Perform EXACTLY ONE action per response. Never chain two tool calls in one turn.\n"
    "- After that single action, print what you observed (the promoted fields you got back), "
    "then STOP and ask me for the exact reply string you want, and WAIT. Do not proceed on "
    "your own.\n"
    "- Wait for my reply (READY, a value, or a short answer) before the next action. If I "
    "say something unexpected, ask again rather than guessing.\n"
    "- If a step fails, do NOT skip ahead: explain what failed in one short line, tell me "
    "the ONE thing to check, and wait for READY.\n"
    "- Keep every response short: one small HTML banner line, the observation, then the "
    "question.\n"
    "- Use ONLY these tools: chat_agent_executer, chat_agent_window_present, "
    "chat_agent_windower, chat_agent_mouser, chat_agent_keyboarder.\n\n"
    "THE STEPS (one per turn, waiting for me in between):\n\n"
    "Step 1 - Say hello and confirm the room is ready. Print a small HTML banner reading "
    "'DESKTOP FIRST STEPS' and one line telling me this wizard will open Notepad, move it, "
    "type into it and close it without saving. Then ask me to reply exactly READY when I can "
    "see my desktop. WAIT.\n\n"
    "Step 2 - Open a window to work with. Call chat_agent_executer with script='notepad' and "
    "non_blocking=true. Report only whether the launch call returned. Then ask me to reply "
    "exactly READY once I SEE the Notepad window on screen. WAIT.\n\n"
    "Step 3 - Prove Tlamatini can see that window. Call chat_agent_window_present with "
    "window_title='Notepad'. Report whether it was found. Then ask me to reply exactly READY. "
    "WAIT.\n\n"
    "Step 4 - Stage the window where I can watch it. Call chat_agent_windower with "
    "action='move_resize' and window_title='Notepad' and pos_x=360 and pos_y=180 and "
    "width=900 and height=560 and activate_after=true. Report the promoted state, left, top, "
    "width, height. Then ask me to reply exactly READY once I SAW it jump to that position. "
    "WAIT.\n\n"
    "Step 5 - Place the caret with the MOUSE. Call chat_agent_mouser with "
    "movement_type='click_at_window' and window_title='Notepad' and window_anchor='center' "
    "and button_click='left'. Report the promoted located_via, clicked, end_posx, end_posy. "
    "Then ask me to reply exactly READY once I SAW the pointer move and click. WAIT.\n\n"
    "Step 6 - Type with the KEYBOARD. Call chat_agent_keyboarder with "
    "input_sequence=\"'TLAMATINI', enter, 'in ixtli, in yollotl', enter, 'the face, the heart "
    "-- that is wisdom'\" and stride_delay=70 so I can watch each key land. Report that the "
    "sequence was sent. Then ask me to reply exactly READY once I SEE those three lines "
    "inside Notepad. WAIT.\n\n"
    "Step 7 - One visible window move. Call chat_agent_windower with action='arrange' and "
    "arrange_mode='left' and window_title='Notepad' and activate_after=true. Report the "
    "promoted state, left, top, width, height. Then ask me to reply exactly READY once I SAW "
    "it snap to the left half. WAIT.\n\n"
    "Step 8 - One more move, the other way. Call chat_agent_windower with action='maximize' "
    "and window_title='Notepad' and activate_after=true. Report the promoted state and "
    "geometry. Then ask me to reply exactly READY once I SAW it fill the screen. WAIT.\n\n"
    "Step 9 - Ask permission to clean up. Do NOT call anything yet. Just tell me you are "
    "about to close Notepad WITHOUT saving the typed text, and ask me to reply exactly CLOSE "
    "to proceed (or SKIP to leave the window open). WAIT.\n\n"
    "Step 10 - Clean up, only if I replied CLOSE. Call chat_agent_windower with "
    "action='close' and window_title='Notepad'. If a 'Save changes?' dialog appears, dismiss "
    "it WITHOUT saving via chat_agent_keyboarder with input_sequence=\"alt+n\". Report what "
    "happened. Then ask me to reply exactly READY. WAIT. (If I replied SKIP, close nothing "
    "and go straight to Step 11.)\n\n"
    "Step 11 - Wrap up. Render one small HTML table with class='exec-report-table' titled "
    "'Desktop First Steps' and two columns step / result, one row per step 2..10 saying what "
    "happened (launched / found / staged at (left,top) size WxH / clicked at (x,y) / typed 3 "
    "lines / snapped left / maximized / closed or skipped). Keep every body cell "
    "light-background with dark text (background:#ffffff;color:#0f172a; or striped #f1f5f9). "
    "Under it, print one line: 'Next, try the WINDOW SPOTLIGHT demo - it runs these same "
    "Windower moves unattended.' End with END-RESPONSE."
)

GAMES_3D = (
    "Tlamatini, run the 3D BRIDGES - GUIDED FIRST CONTACT wizard with me, please. Before you "
    "send anything, tick BOTH the Multi-Turn checkbox AND the Step-by-Step checkbox. This is "
    "a guided, hands-on wizard: you perform exactly ONE action, then you STOP and WAIT for "
    "me to reply before you do anything else. Do NOT run ahead, do NOT batch two actions "
    "into one turn, do NOT plan the whole run and execute it unattended. If I do not reply, "
    "you wait.\n\n"
    "RULES FOR THE WHOLE WIZARD (read once, obey every turn):\n"
    "- ONE action per turn. After each action, print (a) what you just did, (b) the raw "
    "status you got back, (c) exactly what I should type back, then STOP and wait for me.\n"
    "- The only tools you may use are chat_agent_blenderer (Blender MCP add-on socket) and "
    "chat_agent_unrealer (Unreal MCP at 127.0.0.1:55557). Do NOT use chat_agent_executer, "
    "chat_agent_pythonxer, execute_command or acp_spawn anywhere in this wizard.\n"
    "- Everything here is SAFE and additive: we read, we add ONE probe object, we take a "
    "screenshot. We never delete, never overwrite, never save over my level, never touch a "
    "remote host.\n"
    "- If a step comes back with status='error', do NOT abort the wizard and do NOT retry in "
    "a loop. Report the error verbatim, tell me the one-line fix, and ask me whether to SKIP "
    "that engine and continue.\n"
    "- Never claim a step succeeded unless you actually read an ok status out of the "
    "INI_SECTION_BLENDERER / INI_SECTION_UNREALER block in the run's log_excerpt.\n\n"
    "STEP 1 - Ask me first, run nothing.\n"
    "Ask me which 3D app I have open right now and wait for my answer: I will reply exactly "
    "one of BLENDER, UNREAL, BOTH, or NEITHER. If I answer NEITHER, tell me to open Blender "
    "(with the Blender MCP add-on enabled, Online access on, server started) or an Unreal "
    "Engine 5 project (its UnrealMCP plugin auto-binds 127.0.0.1:55557 when the editor "
    "starts), then wait for me to reply READY. Do not call any tool in this step.\n\n"
    "STEP 2 - Probe Blender (only if I said BLENDER or BOTH; otherwise say you are skipping "
    "it and go to Step 3).\n"
    "Make ONE call: chat_agent_blenderer with request \"Run Blender command with "
    "command='ping'\". Report the status and, on ok, the Blender version string and the scene "
    "name, both verbatim. Then STOP and wait for me to reply READY.\n\n"
    "STEP 3 - Probe Unreal (only if I said UNREAL or BOTH; otherwise say you are skipping it "
    "and go to Step 6).\n"
    "Make ONE call: chat_agent_unrealer with request \"Run Unreal command with "
    "command='get_current_level'\". Report the level name and the actor count verbatim - this "
    "is our BEFORE baseline. If it errors, tell me the listener is probably not bound and "
    "that I should check the UE Output Log for 'UnrealMCP listening on 127.0.0.1:55557'. "
    "Then STOP and wait for me to reply READY.\n\n"
    "STEP 4 - Add one harmless probe object to the Unreal level.\n"
    "Make ONE call: chat_agent_unrealer with request \"Run Unreal command with "
    "command='spawn_actor' and params.name='HelloTlamatini_Cube' and "
    "params.type='StaticMeshActor' and params.location=[0,0,250] and "
    "params.rotation=[0,0,0]\". Report the status verbatim. Tell me a freshly spawned "
    "StaticMeshActor has no mesh yet, so in the viewport it appears as a bare actor - that "
    "is expected and NOT an error. Then ask me to look at my Unreal World Outliner and reply "
    "READY once I can see HelloTlamatini_Cube in the list. WAIT for that.\n\n"
    "STEP 5 - Look at what we changed.\n"
    "Make ONE call: chat_agent_unrealer with command='take_screenshot', passing as "
    "params.filepath an absolute path INSIDE Tlamatini's own Temp directory (the Temp folder "
    "at the application root - the system prompt gives you its absolute path; never write to "
    "C:/Temp or the system temp), with the filename hello_tlamatini_first_contact.png. "
    "Report the saved path the plugin returns. Then ask me to open that .png and reply with "
    "one line describing what I see. WAIT for my reply.\n\n"
    "STEP 6 - Close the wizard.\n"
    "Emit a compact HTML table with class='exec-report-table' titled 'First Contact - Run "
    "Report', one row per tool call actually made, columns: step, engine (blender|unreal), "
    "command, status (verbatim, never re-classified), headline. Keep every body cell "
    "light-background with dark text (background:#ffffff;color:#0f172a). Under it print one "
    "line summarising: blender ok|error|skipped, unreal ok|error|skipped, the level name, "
    "the actor count before, and the screenshot path. Finally tell me, in one sentence each, "
    "which prompt in this section to run next: the Blender Forge demo if only Blender "
    "answered, the Unreal Snapshot demo if only Unreal answered, and - if I have no Unreal "
    "project at all - the Unreal 5.8 project scaffolder prompt first.\n\n"
    "Cleanup note (informational, NOT a step): this wizard leaves exactly one artifact "
    "behind, the actor HelloTlamatini_Cube, and it deliberately does NOT save the level, so "
    "simply closing without saving discards it; otherwise right-click it in the World "
    "Outliner and delete it yourself.\n\n"
    "End with END-RESPONSE."
)

MEDIA_VOICE = (
    "Tlamatini, run the MEDIA &amp; VOICE GUIDED FIRST STEPS wizard, please - this one is "
    "INTERACTIVE. Before sending, tick BOTH the Multi-Turn checkbox AND the Step-by-Step "
    "checkbox (leave ACPX, Ask Execs and Add-internet-context unticked).\n\n"
    "HOW THIS WIZARD WORKS (non-negotiable): you perform EXACTLY ONE action per turn, then "
    "you STOP and WAIT for me. After every single action you must end your turn with a short "
    "line telling me exactly what to reply - 'Reply READY to continue', or 'Reply the "
    "transcript you saw', or 'Reply SKIP if you have no microphone'. Do NOT chain two "
    "actions in one turn. Do NOT run ahead. Do NOT assume my answer. If I reply SKIP, "
    "acknowledge it, mark that step as skipped, and move on to the next step on my NEXT "
    "reply.\n\n"
    "You may use ONLY these three wrapped tools, one per step: chat_agent_talker, "
    "chat_agent_whisperer, chat_agent_camcorder. Do NOT use chat_agent_executer, "
    "chat_agent_pythonxer, acp_spawn or any other tool. Everything here is SAFE: it plays a "
    "short sound, records a few seconds of my own mic, and takes one photo with my own "
    "webcam. Nothing is deleted, nothing is sent to anyone.\n\n"
    "VOICE RULE (by design, non-negotiable): you are FEMALE and you speak ONLY with a female "
    "voice - tara (preferred), leah, jess, mia or zoe.\n\n"
    "TURN 0 (no tool call): print one short HTML banner titled 'MEDIA &amp; VOICE - GUIDED "
    "FIRST STEPS', list the four steps you are about to walk me through in one line each (1 "
    "hear your voice, 2 check my speakers, 3 record my microphone, 4 take one webcam photo), "
    "and tell me: 'Reply READY when you want to start with Step 1.' Then STOP.\n\n"
    "TURN 1 - after I reply READY: call chat_agent_talker EXACTLY ONCE with request \"Speak "
    "with input_text='Hello Angela, this is my voice. Can you hear me?' and voice='tara'\". "
    "Then, from the INI_SECTION_TALKER block in the run's log_excerpt, report verbatim: "
    "voice, gender, status (spoken | saved | tokens_only | error), audio_seconds and "
    "output_path. If status is tokens_only, say plainly that this is a documented degraded "
    "mode (no vocoder or no reachable Ollama), NOT a failure. Then ask: 'Did you HEAR me? "
    "Reply YES or NO.' Then STOP.\n\n"
    "TURN 2 - after I answer YES or NO: do NOT call any tool. If I said YES, confirm the "
    "speaker path works and name the saved WAV. If I said NO, give me exactly ONE thing to "
    "check first (speaker volume / default output device / whether status was tokens_only), "
    "and nothing more. Either way finish with: 'Reply READY to move to Step 3 - your "
    "microphone.' Then STOP.\n\n"
    "TURN 3 - after I reply READY: tell me in ONE sentence that you are about to record 10 "
    "seconds of my microphone and that I should speak a short sentence out loud while it "
    "runs. Then call chat_agent_whisperer EXACTLY ONCE with request \"Transcribe with "
    "input_source='mic' and record_seconds=10 and engine='faster-whisper' and model='base' "
    "and device='auto'\". From the INI_SECTION_WHISPERER block report verbatim: engine, "
    "model, device (cuda/cpu), language, status (transcribed | empty | engine_unavailable | "
    "error), word_count and transcript_path, and quote the recognized text in a blockquote "
    "(or '(no speech detected)'). If status is engine_unavailable, say plainly that "
    "faster-whisper is not installed and no cloud key is set - give the one-line fix 'pip "
    "install faster-whisper' - and treat it as a documented degraded mode, NOT a failure. "
    "Then ask: 'Did I transcribe you correctly? Reply YES, or paste what you actually said.' "
    "Then STOP.\n\n"
    "TURN 4 - after I answer: do NOT call any tool. In two lines at most, compare what I "
    "said with what you heard and say whether the microphone path is working. Then finish "
    "with: 'Reply READY for the last step - one webcam photo.' Then STOP.\n\n"
    "TURN 5 - after I reply READY: call chat_agent_camcorder EXACTLY ONCE with request "
    "\"Capture with capture_mode='photo' and camera_index=0 and warmup_seconds=1\". From the "
    "INI_SECTION_CAMCORDER block report verbatim: media_type, camera_index, resolution, "
    "output_path. Then ask: 'Open that file and tell me - do you see yourself? Reply YES or "
    "NO.' Then STOP.\n\n"
    "TURN 6 - after I answer: do NOT call any tool. Render ONE final HTML table with "
    "class='exec-report-table' titled 'Media &amp; Voice - Readiness Report' with columns step, "
    "agent, status, evidence - one row per step actually attempted (Talker, Whisperer, "
    "Camcorder), every value verbatim from the INI_SECTION_* blocks, plus any step I marked "
    "SKIP shown as skipped. Light body cells (background:#ffffff;color:#0f172a), green tint "
    "for a working path, amber tint for a documented degraded mode (tokens_only / "
    "engine_unavailable), and NEVER re-classify a value. Underneath, print one closing line "
    "naming which of my three media paths (speakers / microphone / webcam) are ready, and "
    "point me at the next prompts in this section: 'Tlamatini Speaks' for the full voice "
    "demo, 'Tlamatini Listens' for the full transcription demo. End with END-RESPONSE."
)

# (idPrompt, category, content) — appended at 98..106, each at the reserved opener rank.
_NEW_PROMPTS = (
    (98, 'files_search', FILES_SEARCH),
    (99, 'run_execute', RUN_EXECUTE),
    (100, 'code_gen', CODE_GEN),
    (101, 'images', IMAGES),
    (102, 'agents_flows', AGENTS_FLOWS),
    (103, 'acpx_skills', ACPX_SKILLS),
    (104, 'desktop_ui', DESKTOP_UI),
    (105, 'games_3d', GAMES_3D),
    (106, 'media_voice', MEDIA_VOICE),
)


def add_openers(apps, schema_editor):
    Prompt = apps.get_model('agent', 'Prompt')
    for pid, category, content in _NEW_PROMPTS:
        Prompt.objects.update_or_create(
            idPrompt=pid,
            defaults={
                'promptName': f'prompt-{pid}',
                'promptContent': content,
                'category': category,
                'hidden': False,
                'sort_rank': OPENER_RANK,
            },
        )


def remove_openers(apps, schema_editor):
    Prompt = apps.get_model('agent', 'Prompt')
    Prompt.objects.filter(idPrompt__in=[pid for pid, _c, _t in _NEW_PROMPTS]).delete()


class Migration(migrations.Migration):

    dependencies = [('agent', '0181_prompt_sort_rank')]

    operations = [migrations.RunPython(add_openers, remove_openers)]
