# ═══════════════════════════════════════════════════════════════════
#   ✦  T L A M A T I N I  ✦   —   "one who knows"
#
#   Created by  Angela López Mendoza   ·   @angelahack1
#   Developer · Architect · Creator of Tlamatini
#
#   Every line of this file was written by Angela López Mendoza.
# ═══════════════════════════════════════════════════════════════════
#   Tlamatini Author Banner — do not remove (releases scrub the name automatically)
"""
Django settings for tlamatini project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
import time

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Tlamatini Temp policy ────────────────────────────────────────────────────
# Pin ALL temporary files to ``<application-root>/Temp`` so nothing ever leaks
# to ``C:\Temp`` / ``%TEMP%``.  manage.py already does this before Django on the
# normal launch paths; this repeats it (idempotently) in settings so a DIRECT
# ``daphne tlamatini.asgi:application`` / ``uvicorn`` launch that bypasses
# manage.py is still covered.  Self-contained, fail-open; resolution matches
# manage.py::_enforce_app_temp_dir and agent/path_guard.py::_get_application_root
# (frozen → exe dir; source → repo root = the dir above this Django project).
def _pin_temp_directory():
    try:
        if getattr(sys, 'frozen', False):
            _temp_base = Path(sys.executable).resolve().parent
        else:
            _temp_base = BASE_DIR.parent
        _temp_root = _temp_base / 'Temp'
        _temp_root.mkdir(parents=True, exist_ok=True)
        _temp_root_str = str(_temp_root)
        for _var in ('TMP', 'TEMP', 'TMPDIR'):
            os.environ[_var] = _temp_root_str
        os.environ['TLAMATINI_TEMP'] = _temp_root_str
        import tempfile
        tempfile.tempdir = _temp_root_str
        # Templates: default parent for firmware/engine agent scaffold projects.
        _templates_root = _temp_base / 'Templates'
        _templates_root.mkdir(parents=True, exist_ok=True)
        os.environ['TLAMATINI_TEMPLATES'] = str(_templates_root)
        # Frozen: pool agents run on the CARRIED Python (<install>/python); force them
        # to ignore any stray per-user site-packages (%APPDATA%/Python) so they run
        # COMPLETELY on the carried interpreter's own libs. Inherited by every child.
        # Per-user lib dirs that use PYTHONPATH (e.g. ESPHomer's esphome-lib) are NOT
        # affected. Source mode is left alone (dev relies on its environment).
        if getattr(sys, 'frozen', False):
            os.environ['PYTHONNOUSERSITE'] = '1'
    except Exception:
        pass


_pin_temp_directory()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$f=fy&i80tqgzy%#^x@^am%)duwk7qq5_*807l)mtrsj$$7wk'

# SECURITY WARNING: don't run with debug turned on in production!
# ── Runtime mode: RELEASE vs DEBUG (speed batch, 2026-07-02) ─────────────────
# Frozen installs (the packaged .exe) default to RELEASE (DEBUG=False): Django
# skips per-request debug bookkeeping (query tracking, debug error pages, the
# dev static handler) and WhiteNoise serves static files with release caching.
# Source/development runs keep DEBUG=True so day-to-day development stays
# friendly. Overrides:
#   * TLAMATINI_RELEASE=1     → a SOURCE run behaves like a release build
#                               (test release mode without packaging).
#   * TLAMATINI_DJANGO_DEBUG  → emergency override in EITHER direction
#                               (=1 forces DEBUG even on a frozen install,
#                                =0 forces release even in source mode).
# In RELEASE the browser gets a friendly error page + short error id while the
# FULL traceback still lands in tlamatini.log — see FriendlyErrorMiddleware
# (tlamatini/middleware.py) and the LOGGING guarantee below.
_TRUTHY = {'1', 'true', 'yes', 'on'}
_release_mode = (
    getattr(sys, 'frozen', False)
    or os.environ.get('TLAMATINI_RELEASE', '').strip().lower() in _TRUTHY
)
_debug_override = os.environ.get('TLAMATINI_DJANGO_DEBUG')
if _debug_override is not None and _debug_override.strip() != '':
    DEBUG = _debug_override.strip().lower() in _TRUTHY
else:
    DEBUG = not _release_mode

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agent',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Friendly release error pages: unhandled view exceptions become a small
# branded page (or JSON) + short error id, while the FULL traceback goes to
# tlamatini.log. FIRST in the list = its process_exception runs LAST (Django
# calls them bottom-up), so it only sees what nothing else handled. In DEBUG
# it stands aside so Django's technical debug page keeps working.
MIDDLEWARE.insert(0, 'tlamatini.middleware.FriendlyErrorMiddleware')

# HTML no-cache in BOTH modes (DEBUG used to be always-on, so this simply
# preserves the behavior every install has today): pages always revalidate,
# so a self-update is picked up on the next click, while static assets stay
# cached (they cache-bust via the ?v={{ STATIC_VERSION }} query parameter).
MIDDLEWARE.append('tlamatini.middleware.NoCacheHTMLMiddleware')

# Per-line USER attribution in tlamatini.log (Angela, 2026-08-13). Appended, so
# it sits CLOSEST to the view: it binds the logged-in user immediately before
# the view runs and unbinds immediately after, and it never executes for a
# request WhiteNoise already served. See agent/log_identity.py.
MIDDLEWARE.append('tlamatini.middleware.UserLogTagMiddleware')

ROOT_URLCONF = 'tlamatini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tlamatini.context_processors.static_version',
                'tlamatini.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'tlamatini.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # WAL: crash-safe journalling; many readers alongside one
        # writer. Persistent once set on the file. Under WAL, back up
        # with sqlite3's online backup API, never a plain file copy.
        'OPTIONS': {
            'init_command': (
                'PRAGMA journal_mode=WAL;'
                'PRAGMA synchronous=NORMAL;'
                'PRAGMA busy_timeout=5000;'
            ),
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-MX'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use an absolute URL path for static files
STATIC_URL = '/static/'

# Default location where collectstatic will place files during development
STATIC_ROOT = BASE_DIR / "staticfiles"

# When running as a PyInstaller-frozen app, static files live alongside the executable
if getattr(sys, 'frozen', False):
    frozen_base_dir = Path(getattr(sys, '_MEIPASS', Path(sys.executable).parent))
    STATIC_ROOT = frozen_base_dir / "staticfiles"

# Version stamp for cache-busting of static assets in templates
# Override via env var STATIC_VERSION when deploying
STATIC_VERSION = os.environ.get('STATIC_VERSION') or str(int(time.time()))

# WhiteNoise configuration: dev vs release.
# NOTE (speed batch, 2026-07-02): the old per-branch STATICFILES_STORAGE lines
# were removed — Django 5.1+ deleted that setting (STORAGES replaced it), so
# they never took effect. The default static storage keeps file NAMES
# unchanged: no manifest hashing, no staticfiles.json requirement, so a frozen
# install can never 500 on a missing/stale manifest. Cache busting comes from
# the ?v={{ STATIC_VERSION }} query parameter (context processor
# static_version), which changes on every server start, so a modest MAX_AGE is
# safe across self-updates.
if DEBUG:
    WHITENOISE_AUTOREFRESH = True   # re-stat files per request (dev comfort)
    WHITENOISE_MAX_AGE = 0
else:
    WHITENOISE_AUTOREFRESH = False  # scan once at startup — no per-request stat calls
    WHITENOISE_MAX_AGE = 60         # names are NOT hashed → keep re-validation quick
    if not getattr(sys, 'frozen', False):
        # A SOURCE run in release mode (TLAMATINI_RELEASE=1): serve the
        # CURRENT app static files via the staticfiles finders, so no
        # collectstatic pass is needed to test release behavior. Frozen
        # installs serve the collected STATIC_ROOT tree shipped next to
        # the executable (build.py runs collectstatic).
        WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# myproject/settings.py
ASGI_APPLICATION = 'tlamatini.asgi.application'

LOGIN_URL = 'home'

# Channel Layer configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Logging configuration – ensures that agent.chat_agent_runtime, agent.tools,
# and agent.mcp_agent INFO-level messages are visible in the console.
#
# USEFUL-LOG GUARANTEE (speed batch, 2026-07-02): with DEBUG=False Django's
# DEFAULT logging config hides its console handler behind require_debug_true —
# 500 tracebacks would silently stop reaching the console (and therefore
# tlamatini.log, which tees the console). The explicit "django" logger below
# has NO debug filter, so request/server lines and FULL error tracebacks land
# in tlamatini.log in BOTH modes. "tlamatini.request" is the logger
# FriendlyErrorMiddleware uses (error id + request path + traceback for
# release-mode 500s). The root logger catches everything else that has no
# handler of its own — asyncio/background-thread errors included — at
# TLAMATINI_LOG_LEVEL (default WARNING, so third-party INFO noise stays out;
# set TLAMATINI_LOG_LEVEL=DEBUG or INFO to restore deeper runtime logs).
_LOG_LEVEL = (os.environ.get('TLAMATINI_LOG_LEVEL') or 'WARNING').strip().upper()
if _LOG_LEVEL not in {'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'}:
    _LOG_LEVEL = 'WARNING'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "suppress_http_get_200": {
            "()": "tlamatini.logging_filters.SuppressHttpGet200",
        },
    },
    "formatters": {
        "chat_runtime": {
            "format": "%(asctime)s [%(name)s] %(levelname)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "chat_runtime",
        },
    },
    # Catch-all: any logger without its own handler (asyncio, channels,
    # daphne, third-party libs, background threads) propagates here, so
    # warnings/errors are GUARANTEED to reach the console → tlamatini.log.
    "root": {
        "handlers": ["console"],
        "level": _LOG_LEVEL,
    },
    "loggers": {
        # No require_debug_true filter (unlike Django's default config):
        # request lines and FULL 500 tracebacks stay in tlamatini.log even
        # in RELEASE mode (DEBUG=False).
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # FriendlyErrorMiddleware's logger: error id + method/path + full
        # traceback for release-mode unhandled view exceptions.
        "tlamatini.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.chat_agent_runtime": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.tools": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.mcp_agent": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Ask-Execs permission broker. Without this entry it inherits the ROOT level
        # (WARNING), so "[ExecPermissionBroker] cancel detected; denying …" is dropped
        # and it LOOKS like the broker never honoured the cancel — it did, we just
        # could not see it. An observability gap that cost real debugging time.
        # (Angela, 2026-07-14)
        "agent.exec_permission": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.global_execution_planner": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "agent.capability_registry": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.channels.server": {
            "filters": ["suppress_http_get_200"],
        },
    },
}